inveniosoftware/react-invenio-app-ils

src/lib/modules/Loan/actions.js
src/lib/pages/backoffice/Item/ItemDetails/ItemActionMenu/ItemActionMenu.js
src/lib/pages/backoffice/Item/ItemDetails/ItemDetails.js
src/lib/pages/backoffice/Item/ItemDetails/ItemPendingLoans/ItemPendingLoans.js
src/lib/pages/backoffice/Item/ItemDetails/ItemPendingLoans/ItemPendingLoans.test.js
src/lib/pages/backoffice/Item/ItemDetails/ItemPendingLoans/__snapshots__/ItemPendingLoans.test.js.snap
src/lib/pages/backoffice/Item/ItemDetails/ItemPendingLoans/index.js

* Adds new box in the item detail page to
show the list of loan requests and the
checkout button for each one
* closes #85
--------------
-------------
-------------
-------------

backoffice: Adds loan request to item details page

---

src/lib/api/patrons/patron.js
src/lib/api/patrons/patron.test.js
src/lib/api/patrons/serializer.js
src/lib/components/Loader/Loader.js
src/lib/components/backoffice/Sidebar/Sidebar.js
src/lib/config/__mocks__/index.js
src/lib/config/defaultConfig.js
src/lib/modules/ESSelector/ESSelector.js
src/lib/modules/ESSelector/ESSelectorModal.js
src/lib/modules/ESSelector/HitsSearch.js
src/lib/modules/Loan/backoffice/LoanList/LoanList.js
src/lib/pages/backoffice/Actions/CheckIn/ItemsSearch/ItemsSearch.js
src/lib/pages/backoffice/Actions/CheckOut/CheckOut.js
src/lib/pages/backoffice/Actions/CheckOut/CheckOutResults/CheckOutResults.js
src/lib/pages/backoffice/Actions/CheckOut/CheckOutResults/ItemList.js
src/lib/pages/backoffice/Actions/CheckOut/CheckOutResults/PatronList.js
src/lib/pages/backoffice/Actions/CheckOut/CheckOutResults/index.js
src/lib/pages/backoffice/Actions/CheckOut/CheckOutSearch/CheckOutSearch.js
src/lib/pages/backoffice/Actions/CheckOut/CheckOutSearch/index.js
src/lib/pages/backoffice/Actions/CheckOut/reducer.js
src/lib/pages/backoffice/Actions/CheckOut/state/actions.js
src/lib/pages/backoffice/Actions/CheckOut/state/actions.test.js
src/lib/pages/backoffice/Actions/CheckOut/state/reducer.js
src/lib/pages/backoffice/Actions/CheckOut/state/reducer.test.js
src/lib/pages/backoffice/Item/ItemDetails/ItemActionMenu/ItemActionMenu.js
src/lib/pages/backoffice/Item/ItemDetails/ItemActionMenu/index.js
src/lib/pages/backoffice/Patron/PatronDetails/ItemsSearch/ItemsSearch.js
src/lib/routes/backoffice/BackOfficeRoutesSwitch.js
src/lib/routes/backoffice/backofficeUrls.js
src/lib/store.js

- search bar with search in two indices
- fix patron api list bug with suffixed *
- configurable scan field for Patron search
- results for items and patrons
- checkout search reducer with patron and item
- fix: in PatronDetails if we search for item and is eligible for loan, then we the auto check-out
- demo placeholders
- patron result table with support for configured scan field
- search modal open when auto check-out item scanned
- fix ESSElectorModal propTypes errors
- ESSelector onResults hook
- prevent empty searches
- search on all available props of patron
- closes #36

backoffice: checkout

---

src/lib/config/common.js
src/lib/config/defaultConfig.js
src/lib/modules/SearchControls/SearchAggregationsCards.js
src/lib/pages/backoffice/Location/LocationForms/LocationEditor/LocationEditor.js
src/lib/pages/frontsite/Documents/DocumentDetails/DocumentDetails.js
src/lib/pages/frontsite/Documents/DocumentDetails/index.js
src/lib/pages/frontsite/Series/SeriesDetails/SeriesDetails.js
src/lib/pages/frontsite/Series/SeriesDetails/index.js

* displays 404 page when literature or series is not found on the frontsite (closes #42)
* removed "Restricted" facet from the frontsite search (closes #108)
* support for configurable search filters labels, renamed the "Relation" filter (closes #109)
* repaired link to location editor

global: minor fixes

---

src/lib/config/defaultConfig.js

* added config fields to allow sorting the catalogue by titles (available in both frontsite and backoffice)
* depends on inveniosoftware/invenio-app-ils#923
* closes #111

search: sort by title

---

src/lib/config/common.js
src/lib/modules/Document/DocumentInfo.js
src/lib/modules/ESSelector/ESSelectorModal.js
src/lib/pages/backoffice/Loan/LoanDetails/LoanActions/LoanActions.js
src/lib/pages/frontsite/PatronProfile/PatronOverview/PatronOverview.js

* fixed a typo
* added a prop to selector modal to disallow empty selections (closes #105)
* fixed config client/server mismatch (closes #129)
* fixed trailing comma in enumeration (closes #94)
* patron page: added loading state to statistics
(loading state)
(final state; note that the alignment stays the same)

global: minor tweaks + patron page statistics loading

---

src/lib/modules/Document/DocumentTags.js
src/lib/modules/Document/backoffice/DocumentList/DocumentListEntry.js
src/lib/pages/backoffice/Document/DocumentDetails/DocumentHeader.js
src/lib/pages/backoffice/Document/DocumentDetails/DocumentMetadata/DocumentMetadataGeneral.js
src/lib/pages/backoffice/Series/SeriesDetails/SeriesHeader.js
src/lib/pages/backoffice/Series/SeriesSearch/SeriesListEntry.js

* Adds new prop to `DocumentTags`
* Fixes the redirection of the tags
* closes #18

backoffice: Fixes tags redirection

---

src/lib/components/backoffice/ExportSearchResults/ExportSearchResults.js
src/lib/components/backoffice/buttons/ScrollingMenu/ScrollingMenu.js
src/lib/modules/Document/DocumentAuthors.js
src/lib/modules/ESSelector/ESSelector.js
src/lib/modules/ESSelector/ESSelectorLoanRequest.js
src/lib/modules/ESSelector/HitsSearch.js
src/lib/modules/Literature/LiteratureCover.js
src/lib/modules/SearchControls/overridden/SearchSortOrderElementMobile.js
src/lib/modules/Series/__snapshots__/SeriesCard.test.js.snap
src/lib/pages/backoffice/ILL/BorrowingRequest/BorrowingRequestDetails/BorrowingRequestPatronLoan/BorrowingRequestPatronLoan.js
src/lib/pages/backoffice/Item/ItemDetails/ItemPendingLoans/ItemPendingLoans.js
src/lib/pages/backoffice/Loan/LoanDetails/LoanMetadata/LoanMetadata.js
src/lib/pages/frontsite/Documents/DocumentDetails/DocumentPanel/DocumentPanel.js
src/lib/pages/frontsite/PatronProfile/PatronCurrentDocumentRequests/PatronCurrentDocumentRequests.js
src/lib/pages/frontsite/PatronProfile/PatronPastDocumentRequests/PatronPastDocumentRequests.js

* addresses #172
* DocumentAuthors component raising exception
* "checkout" button in loan requests not disabled during loading
* LiteratureCover flickering on page change (closes #135)
* hide navigation buttons in patron loans on empty result set
* BorrowingRequestPatronLoan state not reset
* ESSelectorLoanRequest request button not disabled
* SearchSortOrderElementMobile uninitialized attribute
* ExportSearchResults not starting from the first page
* ScrollingMenu first element not selected due to typo
* HitsSearch & ESSelector toggleable initial focus, disabled by default
* LoanMetadata invalid dates displayed

Minor bugfixes

---

src/lib/components/backoffice/MetadataTable/MetadataTable.js
src/lib/components/backoffice/UrlList/UrlList.js
src/lib/components/backoffice/icons/Icons.js
src/lib/forms/core/GroupField.js
src/lib/forms/core/SelectorField.js
src/lib/modules/Document/DocumentCard/DocumentCard.js
src/lib/modules/Document/backoffice/DocumentList/DocumentListEntry.js
src/lib/modules/ESSelector/ESSelector.js
src/lib/modules/Literature/LiteratureTags.js
src/lib/modules/Relations/backoffice/components/RelationCard/DocumentCard.js
src/lib/modules/Relations/backoffice/components/RelationCard/SeriesCard.js
src/lib/modules/Relations/backoffice/components/RelationListEntry.js
src/lib/pages/backoffice/Acquisition/Order/OrderDetails/OrderDetails.js
src/lib/pages/backoffice/Acquisition/Order/OrderEditor/OrderForm/OrderInfo.js
src/lib/pages/backoffice/Acquisition/Order/OrderEditor/OrderForm/OrderLines.js
src/lib/pages/backoffice/Document/DocumentForms/DocumentEditor/DocumentForm/DocumentBasicMetadata.js
src/lib/pages/backoffice/DocumentRequest/DocumentRequestDetails/DocumentRequestSteps/ProviderStep/ProviderStep.js
src/lib/pages/backoffice/EItem/EItemForms/EItemEditor/EItemForm/EItemForm.js
src/lib/pages/backoffice/ILL/BorrowingRequest/BorrowingRequestEditor/BorrowingRequestForm/OrderInfo.js
src/lib/pages/backoffice/Item/ItemDetails/ItemCirculation/ItemCirculation.js
src/lib/pages/backoffice/Item/ItemForms/ItemEditor/ItemForm/ItemForm.js
src/lib/pages/backoffice/Loan/LoanDetails/LoanMetadata/LoanMetadata.js
src/lib/pages/backoffice/Location/LocationForms/InternalLocationEditor/components/InternalLocationForm/InternalLocationForm.js
src/lib/pages/backoffice/Series/SeriesForms/SeriesEditor/components/SeriesForm/SeriesForm.js
src/lib/pages/frontsite/Home/Sections/SectionServices.js
src/semantic-ui/site/elements/container.overrides

* fixed dynamic links (closes #25)
* fixed some react related errors
* improved ESSelector component (addresses #191)
* refactoring (using the dedicated icon components when possible)

UX improvements

---

src/lib/components/SearchBar/SearchBar.js
src/lib/components/SearchBar/__snapshots__/SearchBar.test.js.snap
src/lib/index.js
src/lib/pages/backoffice/Patron/PatronDetails/ItemsSearch/ItemsSearch.js
src/lib/pages/backoffice/Patron/PatronDetails/PatronActionMenu/PatronActionMenu.js
src/lib/pages/backoffice/Patron/PatronDetails/PatronDetails.js

- NEW overridable components for Patron details metadata and action menu item
- FIX currentQueryString and executeSearch Warning: React does not recognize the prop on a DOM element. Also props that were passed from the parent were ignored.
- BETTER global export ScrollingMenuItem and MetadataTable
- addresses CERNDocumentServer/cds-ils#145
- required by CERNDocumentServer/cds-ils#149

backoffice: patron details overridable metadata

---

src/lib/components/backoffice/Sidebar/Sidebar.js
src/lib/modules/Document/backoffice/DocumentList/DocumentListEntry.js
src/lib/modules/Literature/LiteratureTags.js
src/lib/modules/Series/SeriesListEntry.js
src/lib/modules/Series/__snapshots__/SeriesListEntry.test.js.snap
src/lib/pages/backoffice/Document/DocumentDetails/DocumentHeader.js
src/lib/pages/backoffice/Document/DocumentDetails/DocumentMetadata/DocumentContents.js
src/lib/pages/backoffice/ILL/BorrowingRequest/BorrowingRequestSearch/BorrowingRequestSearch.js
src/lib/pages/backoffice/Patron/PatronSearch/PatronSearch.js
src/lib/pages/backoffice/Series/SeriesDetails/SeriesContent/SeriesContent.js
src/lib/pages/backoffice/Series/SeriesDetails/SeriesHeader.js
src/lib/pages/backoffice/Series/SeriesSearch/SeriesListEntry.js
src/lib/routes/backoffice/BackOffice.js

- make tags in frontsite/backoffice unclickable
- display tags for series frontsite list view
- fix sidebar active link
- make sidebar links unclickable when active
- add header to borrowing requests and patrons backoffice search pages
Closes #18

LiteratureTags: make them unclickable

---

package-lock.json
package.json
src/lib/forms/core/ObjectListField.js
src/lib/forms/core/SubForm.js
src/lib/modules/ESSelector/ESSelectorLoanRequest.js
src/lib/modules/Location/LocationDatePicker.js
src/semantic-ui/site/collections/form.overrides

- upgrade Formik 2.1.6
- fix propTypes for Subform
- fix activeIndex for ObjectListField
- fix DeleteActionButton overlap with dropdown menus in forms
The delete button `x` of the url should be hidden behind the dropdown or the Role

forms: fix delete button overlap with dropdown

---

package-lock.json
package.json
src/lib/modules/Literature/LiteratureTitle.js
src/lib/pages/backoffice/Patron/PatronDetails/PatronCurrentBorrowingRequests/PatronCurrentBorrowingRequests.js
src/lib/pages/backoffice/Patron/PatronDetails/PatronCurrentBorrowingRequests/PatronCurrentBorrowingRequests.test.js
src/lib/pages/backoffice/Patron/PatronDetails/PatronCurrentBorrowingRequests/__snapshots__/PatronCurrentBorrowingRequests.test.js.snap
src/lib/pages/backoffice/Patron/PatronDetails/PatronPastBorrowingRequests/__snapshots__/PatronPastBorrowingRequests.test.js.snap
src/lib/pages/backoffice/Patron/PatronDetails/PatronPendingLoans/__snapshots__/PatronPendingLoans.test.js.snap

* Adds width prop to LiteratureTitle
* Adds "jest-canvas-mock" to test

backoffice: Fixes ILL section in patron details page

---

src/lib/api/base.js
src/lib/components/HttpErrors/HttpError.js
src/lib/components/HttpErrors/HttpErrors.js
src/lib/components/HttpErrors/index.js
src/lib/pages/frontsite/ErrorsPage/ErrorsPage.js
src/lib/pages/frontsite/ErrorsPage/index.js
src/lib/routes/frontsite/Frontsite.js
src/lib/routes/frontsite/frontsiteUrls.js

* Adds global error handler for 404, 429 and 500
* Adds `errorId` prop (sentry id) to the error component

errorHandling: Adds global error handler

---

src/lib/components/EmailLink/EmailLink.js
src/lib/config/defaultConfig.js
src/lib/pages/backoffice/Acquisition/Vendor/VendorDetails/VendorInformation.js
src/lib/pages/backoffice/ILL/Library/LibraryDetails/LibraryInformation.js
src/lib/pages/backoffice/Item/ItemDetails/ItemCirculation/ItemCirculation.js
src/lib/pages/backoffice/Location/LocationDetails/LocationInformation.js
src/lib/pages/backoffice/Patron/PatronDetails/PatronHeader/PatronHeader.js
src/lib/pages/backoffice/Patron/PatronSearch/PatronResultsList.js

Closes #82
Display only names (patron, vendor, library etc.) and signature in mails because librarians might use another language for their emails.
Email button:

global: add params to emails and improve button

---

src/lib/api/documentRequests/documentRequest.js
src/lib/api/documents/document.js
src/lib/api/documents/document.test.js
src/lib/api/loans/loan.js
src/lib/components/backoffice/ExportSearchResults/ExportSearchResults.js
src/lib/config/defaultConfig.js
src/lib/modules/Document/DocumentCard/DocumentCard.js
src/lib/modules/Document/DocumentListEntry/DocumentListEntry.js
src/lib/modules/Document/DocumentListEntry/DocumentListEntry.test.js
src/lib/modules/Document/backoffice/DocumentList/DocumentCirculation.js
src/lib/modules/Document/backoffice/DocumentList/DocumentCirculation.test.js
src/lib/modules/Document/backoffice/DocumentList/__snapshots__/DocumentCirculation.test.js.snap
src/lib/modules/Patron/PatronCurrentLoans/actions.test.js
src/lib/modules/Patron/PatronDocumentRequests/actions.test.js
src/lib/modules/Patron/PatronPastLoans/actions.test.js
src/lib/modules/Patron/PatronPendingLoans/actions.test.js
src/lib/modules/Series/SeriesLiteratureSearch/__snapshots__/SeriesLiteratureSearch.test.js.snap
src/lib/pages/backoffice/Document/DocumentDetails/DocumentSummary/DocumentSummary.js
src/lib/pages/backoffice/Home/lists/PendingOverdueDocumentsList/__snapshots__/PendingOverdueDocumentsList.test.js.snap
src/lib/pages/backoffice/Home/lists/PendingOverdueDocumentsList/state/actions.test.js
src/lib/pages/backoffice/Home/widgets/DocumentCard/__snapshots__/DocumentsCard.test.js.snap
src/lib/pages/backoffice/Home/widgets/DocumentCard/state/actions.test.js
src/lib/pages/backoffice/Patron/PatronDetails/PatronCurrentLoans/__snapshots__/PatronCurrentLoans.test.js.snap
src/lib/pages/backoffice/Patron/PatronDetails/PatronDocumentRequests/__snapshots__/PatronDocumentRequests.test.js.snap
src/lib/pages/frontsite/Documents/DocumentDetails/DocumentCirculation/LoanAvailability.js
src/lib/pages/frontsite/Home/Headline/Headline.js
src/lib/pages/frontsite/Home/Sections/SectionsWrapper.js
src/lib/pages/frontsite/PatronProfile/PatronCurrentDocumentRequests/state/actions.test.js
src/lib/pages/frontsite/PatronProfile/PatronPastDocumentRequests/state/actions.test.js

For reviewers: there are some sort by that ideally would require to add both ASC and DESC (e.g. loan end date), but we need also to keep the text relatively short. What about using icons?
Ideas with emojis (it does not looks super nice...):

global: change sort config

---

src/lib/api/ill/borrowingRequest.js
src/lib/api/ill/serializers.js
src/lib/components/DatePicker/DatePicker.js
src/lib/components/Pagination/Pagination.js
src/lib/components/backoffice/buttons/ScrollingMenu/ScrollingMenu.js
src/lib/forms/core/BaseForm/BaseForm.js
src/lib/forms/core/DateTimeFields/DateInputField.js
src/lib/pages/backoffice/Acquisition/Order/OrderEditor/OrderForm/OrderForm.js
src/lib/pages/backoffice/Document/DocumentForms/DocumentEditor/DocumentForm/DocumentForm.js
src/lib/pages/backoffice/EItem/EItemForms/EItemEditor/EItemForm/EItemForm.js
src/lib/pages/backoffice/Item/ItemForms/ItemEditor/ItemForm/ItemForm.js
src/lib/pages/frontsite/PatronProfile/PatronPendingLoans/PatronPendingLoans.js

* serialize borrowing request responses (closes CERNDocumentServer/cds-ils#189)
* fix patron scrolling menu initial value
* improve yup validation (addresses #243)
* propagate html required property to date picker input
* schema errors (and more generally all errors) are displayed only after submission, instead of after value change
* schemas for orders, items
* revert pagination pages calculation
* fix patron cancel loan page change bug (closes #225)

Major fixes

---

src/lib/forms/core/BaseForm/RecordSerializer.js
src/lib/forms/core/BaseForm/RecordSerializer.test.js
src/lib/forms/core/PriceField.js

* closes #155
The following changes and simplifications were made to the price field in order to finally make it work correctly:
* the serializer recursively clears the nested objects with empty values
* for instance `{ a: { b: '' } }` will become `{}`
* this also fixes other issues with accordions that were touched but eventually left unfilled and collapsed
* in case of a fixed currency, the feature of displaying a label was discarded in favor of the dropdown
* instead of displaying all currencies the dropdown only shows `defaultCurrency` 
* the currency dropdown always contains an empty value <kbd>-</kbd> and defaults to that
* semantic-UI has bogus error popups for grouped inputs; we now make sure the field is at least highlighted red on any error
As an illustration, the following …

fix price field

---

cypress.json
cypress/integration/frontsite/footer.test.spec.js
cypress/integration/frontsite/homepage.test.spec.js
cypress/integration/frontsite/literatureDetails.test.spec.js
cypress/integration/frontsite/literatureRequest.test.spec.js
cypress/integration/frontsite/navbar.test.spec.js
cypress/integration/frontsite/profile.test.spec.js
cypress/integration/frontsite/search.test.spec.js
cypress/support/commands.js
cypress/support/index.js

Added tests for frontsite. 
About this [comment](https://github.com/inveniosoftware/react-invenio-app-ils/pull/240#discussion_r506142014) I thought wrapping the selectors in variables is easier e.g. `const header = '.ui.header'` instead of using ids. 
Removed some status checks e.g. `cy.wait('@loan').should(xhr => expect(xhr.status).to.eq(401));` since we should be testing the ui and not the backend. 
Added custom command to login by making a backend request instead of using the ui ([comment](https://github.com/inveniosoftware/react-invenio-app-ils/pull/240#discussion_r506170328)).

Cypress: add more frontsite tests

---

src/lib/components/Pagination/Pagination.js
src/lib/modules/Relations/backoffice/components/ExistingRelations.js
src/lib/pages/frontsite/PatronProfile/LoansList.js
src/lib/pages/frontsite/PatronProfile/PatronCurrentDocumentRequests/PatronCurrentDocumentRequests.js
src/lib/pages/frontsite/PatronProfile/PatronPastDocumentRequests/PatronPastDocumentRequests.js
src/semantic-ui/site/globals/site.overrides

Tiny PR that aims to revise pagination. It does not make sense to display a button to go to the last page, firstly because in production the last page may not correspond to the last data entry but rather the last match within the allowed window (currently set at 10k).
Semantic-UI does not provide a way to avoid displaying a button for the last page, we can only control the side buttons; thus as suggested by @kprzerwa if we want to avoid rewriting the entire component the easiest solution is to fix it using CSS.
* First modification is to disable the <kbd><<</kbd> and <kbd>>></kbd> buttons, directly in the overriden component (which was conveniently tweaked to be the global pagination component, in a recent PR)
* Second one is to use a CSS selector that searches for a <kbd>…</kbd> at …

pagination: hide last page item

---

src/lib/pages/frontsite/Documents/DocumentDetails/DocumentCirculation/DocumentCirculation.js

This PR pretends to solve this error: `UI error when duplicating literature details tab on frontsite`, but take into account that is not reproducible locally, but is happening on dev and sandbox environments. 
Error on sandbox/dev:

fixes duplication error

---

src/lib/pages/backoffice/Document/DocumentForms/DocumentEditor/DocumentForm/DocumentAdditionalInfo.js
src/lib/pages/backoffice/Document/DocumentForms/DocumentEditor/DocumentForm/DocumentForm.js
src/lib/pages/backoffice/Document/DocumentForms/DocumentEditor/DocumentForm/components/MetadataExtensions.js

* Adds vocabularies to accelerator, experiments and
standard_reviews
Updates the `MetadataExtension` to be able to support vocabularies and organize the extra fields in lines. Also moves these fields inside the `Additional information` section.
Related to https://github.com/CERNDocumentServer/cds-ils/pull/205

backoffice: refactors extra fields of the documents

---

src/lib/api/patrons/patron.js
src/lib/api/patrons/patron.test.js
src/lib/pages/backoffice/Actions/CheckOut/state/actions.js

When searching by an email in the checkout page before there were no results at all when you didn't wrap the email in quotes. Now it shows results without quotes.
Closes partially CERNDocumentServer/cds-ils#214

CheckoutSearch: get results for email without quotes

---

src/lib/modules/Document/DocumentCard/DocumentCard.js
src/lib/modules/Document/DocumentInfo.js
src/lib/modules/Document/DocumentListEntry/DocumentListEntry.js
src/lib/modules/Relations/backoffice/RelationEdition/RelationEditionModal/RelationEditionModal.js
src/lib/modules/Relations/backoffice/components/RelationModal/RelationModal.js
src/lib/pages/backoffice/Document/DocumentDetails/DocumentRelations/RelationLanguages/RelationLanguagesModal/RelationLanguagesModal.js
src/lib/pages/backoffice/Series/SeriesDetails/SeriesRelations/RelationLanguages/RelationLanguagesModal/RelationLanguagesModal.js

When a document/series doesn't have the edition or languages field filled the button to attach a new relation is disabled until the respective field is filled. Also if the edition of a document/series is empty, it is not longer displayed in the frontsite search page documents card.

Relations: disable add relation button, remove empty edition from frontsite document card

---

src/lib/pages/backoffice/Location/LocationForms/LocationEditor/components/LocationForm/Closures/Closures.js
src/lib/pages/backoffice/Location/LocationForms/LocationEditor/components/LocationForm/Closures/HourField.js
src/lib/pages/backoffice/Location/LocationForms/LocationEditor/components/LocationForm/LocationForm.js

* closes inveniosoftware/invenio-app-ils#980, assuming inveniosoftware/invenio-app-ils#981 is already merged (but AFAIK no blocking dependency)
For the sake of simplicity, the two period fields are always there. The user may leave a pair of inputs empty, and it will be filtered out. The consequence is that if the period is defined in the second pair, it will be moved to the first (as illustrated below).
(before submission)
(after submission, when editing again)

backoffice: update location form opening hours

---

src/lib/components/SearchBar/SearchBarILS.js
src/lib/components/SearchBar/__snapshots__/SearchBarILS.test.js.snap
src/lib/pages/backoffice/Loan/LoanDetails/AvailableItems/AvailableItems.js
src/lib/pages/frontsite/Documents/DocumentDetails/DocumentDetails.js
src/lib/pages/frontsite/Home/Headline/HomeSearchBar.js
src/lib/pages/frontsite/Series/SeriesDetails/SeriesDetails.js

* implement loan checkout workflow with barcode reader (closes #235)
* disable search on paste on frontsite (closes #264)
Loan checkout behavior that this PR implements:
* if the librarian scans an item and all the conditions are met for this item to be loaned, then the item is shown in the search results and a checkout action is automatically triggered (as opposed to searching for an item and then clicking on the button)
* the same happens when a barcode is manually typed and submitted (= clicking on the search button or hitting enter)
* an information message indicates the existence of this behavior when it is applicable
* when typing, the search results are updated accordingly (filtered, since no request is performed). That is, all the items having a barcode starting with the query …

search: improve searchbar

---

src/lib/config/defaultConfig.js
src/lib/config/index.js
src/lib/modules/Series/SeriesLiteratureSearch/SeriesLiteratureSearch.js
src/lib/modules/Series/SeriesLiteratureSearch/__snapshots__/SeriesLiteratureSearch.test.js.snap
src/lib/pages/backoffice/Acquisition/Order/OrderSearch/OrderSearch.js
src/lib/pages/backoffice/Acquisition/Vendor/VendorSearch/VendorSearch.js
src/lib/pages/backoffice/Document/DocumentSearch/DocumentSearch.js
src/lib/pages/backoffice/DocumentRequest/DocumentRequestSearch/DocumentRequestSearch.js
src/lib/pages/backoffice/EItem/EItemSearch/EItemSearch.js
src/lib/pages/backoffice/ILL/BorrowingRequest/BorrowingRequestSearch/BorrowingRequestSearch.js
src/lib/pages/backoffice/ILL/Library/LibrarySearch/LibrarySearch.js
src/lib/pages/backoffice/Item/ItemSearch/ItemSearch.js
src/lib/pages/backoffice/Loan/LoanSearch/LoanSearch.js
src/lib/pages/backoffice/Patron/PatronSearch/PatronSearch.js
src/lib/pages/backoffice/Series/SeriesSearch/SeriesSearch.js
src/lib/pages/frontsite/Literature/LiteratureSearch/LiteratureSearch.js

* Adds defaultSortingOnEmptyQueryString prop
to ReactSearchKit component
Adds missing sort filters. 
Updates the behaviour of RSK, now the `initialState` will always be set to "Most relevant" (`bestmatch`) if it exists otherwise the first sort type will be used. For the `defaultSortingOnEmptyQueryString` will always be "Recently added" except for the patrons (because they only allow "bestmatch").
Behaviour of `defaultSortingOnEmptyQueryString` prop tested and it's correct

RSK: integrates latest changes

---

src/lib/api/acquisition/serializers.js
src/lib/api/acquisition/serializers.test.js
src/lib/pages/backoffice/Acquisition/Order/OrderDetails/OrderStatistics.js
src/lib/pages/backoffice/Acquisition/Order/OrderEditor/OrderForm/OrderForm.js
src/lib/pages/backoffice/Location/LocationForms/InternalLocationEditor/components/InternalLocationForm/InternalLocationForm.js

- Fixes internal location form error, when creating or editing it was displaying an error.
- If an ACQ order has status != CANCELLED and does not have a total price (which could be possible because is not a required field) it breaks when accesing the ACQ order details page. Added a check to display the value if it exists.
- If we edit an ACQ with order lines, the document and patron (of the order lines) will not appear even if they already exist and they do exist because they are required fields. Fixed by updating the `data.metadata.order_lines` with the values of `data.metadata.resolved_order_lines`. This makes me wonder why do we have `resolved_order_lines` and `order_lines` ?

backoffice: Fixes internal location form bug

---

src/lib/index.js
src/lib/routes/frontsite/Frontsite.js

- adds overridable routes in frontsite
- exports necessary components to be used in cds-ils ([pr](https://github.com/CERNDocumentServer/cds-ils/pull/228))

Routes: add overridable route

---

src/lib/api/acquisition/order.js
src/lib/api/ill/borrowingRequest.js
src/lib/config/defaultConfig.js
src/lib/index.js
src/lib/pages/backoffice/Acquisition/Order/OrderEditor/OrderEditor.js
src/lib/pages/backoffice/Acquisition/Order/OrderEditor/OrderForm/OrderForm.js
src/lib/pages/backoffice/Document/DocumentForms/DocumentEditor/DocumentEditor.js
src/lib/pages/backoffice/Document/DocumentForms/DocumentEditor/DocumentForm/DocumentForm.js
src/lib/pages/backoffice/DocumentRequest/DocumentRequestDetails/DocumentRequestSteps/ProviderStep/ProviderStep.js
src/lib/pages/backoffice/ILL/BorrowingRequest/BorrowingRequestEditor/BorrowingRequestEditor.js
src/lib/pages/backoffice/ILL/BorrowingRequest/BorrowingRequestEditor/BorrowingRequestForm/BorrowingRequestForm.js

- redirect order and borrowing request forms to literature request form
- add function `listWithPendingStatus` to be used in Provider's ESSelector because previously it displayed all results with `status=PENDING` without taking into account the search query
Closes #290

backoffice: fix the workflow of LiteratureRequest

---

package.json
public/index.html
src/lib/routes/backoffice/BackOfficeRoutesSwitch.js
src/lib/routes/frontsite/Frontsite.js

Closes #312 
- removed `homepage` from package.json because it was setting the static resources url to `https://127.0.0.1/inveniosoftware/react-invenio-app-ils/<static_resource>` instead of `https://127.0.0.1/<static_resource>`
- wrapped Overridable route with NotFound route because before the fallback route was the Overridable instead if the NotFound

Routes: fix not-found route bug

---

cypress/integration/backoffice/document.test.spec.js
cypress/integration/backoffice/loanDetails.test.spec.js
cypress/integration/backoffice/loanSearch.test.spec.js
cypress/integration/frontsite/literatureDetails.test.spec.js
cypress/integration/frontsite/search.test.spec.js
cypress/support/index.js
src/lib/index.js
src/lib/pages/frontsite/Home/Sections/SectionInstallation.js

Includes the following sets of unrelated changes:
* update broken cypress tests
* fix outdated documentation link
* export `ResultsTable` component (will be needed for `cds-ils`)

cypress: update tests & minor changes

---

src/lib/modules/Literature/LiteratureCover.js
src/lib/modules/Series/__snapshots__/SeriesCard.test.js.snap
src/semantic-ui/site/elements/image.overrides

Make the cover frame constant, fit the image in it while preserving the aspect ratio and avoiding overflow. The images are always centred.
Closes #296
Notes:
* this does not apply on mobile, but it applies on the computer stacked view
* I didn't find a way to inherit the height or make it relative to the width, so I hardcoded it (`200px`)
* there is no left/right margins so the wide covers will match the overlay width (typically square or landscape images). I personally don't find it odd but it can be changed if necessary
[A screenshot of the stacked view](https://user-images.githubusercontent.com/9027075/103626245-358d0b00-4f3c-11eb-8a14-a2e51b1cbc4f.png)

covers: alignment on frontsite search

---

package-lock.json
package.json
src/lib/App.js
src/lib/authentication/pages/Login/Login.js
src/lib/components/CancelModal/__snapshots__/CancelModal.test.js.snap
src/lib/components/ILSMenu/ILSMenu.js
src/lib/components/Media/index.js
src/lib/components/Media/media.js
src/lib/modules/Literature/LiteratureSearchResultsGrid.js
src/lib/modules/Relations/backoffice/components/RelationModal/RelationModal.js
src/lib/modules/SearchControls/SearchControls.js
src/lib/modules/SearchControls/SearchFooter.js
src/lib/modules/SearchControls/SearchPagination.js
src/lib/modules/SearchControls/SearchSortBy.js
src/lib/modules/SearchControls/__snapshots__/SearchControls.test.js.snap
src/lib/modules/Series/SeriesLiteratureSearch/SeriesLiteratureSearch.js
src/lib/modules/Series/SeriesLiteratureSearch/__snapshots__/SeriesLiteratureSearch.test.js.snap
src/lib/pages/backoffice/Document/DocumentDetails/DocumentStats/__snapshots__/DocumentStats.test.js.snap
src/lib/pages/frontsite/Documents/DocumentDetails/DocumentDetails.js
src/lib/pages/frontsite/Documents/DocumentDetails/DocumentMetadata/DocumentMetadata.js
src/lib/pages/frontsite/Documents/DocumentDetails/DocumentPanel/DocumentPanel.js
src/lib/pages/frontsite/Literature/LiteratureSearch/LiteratureSearch.js
src/lib/pages/frontsite/PatronProfile/PatronCurrentLoans/__snapshots__/LoanExtendButton.test.js.snap
src/lib/pages/frontsite/Series/SeriesDetails/SeriesDetails.js
src/lib/pages/frontsite/Series/SeriesDetails/SeriesMetadata/SeriesMetadata.js
src/lib/pages/frontsite/Series/SeriesDetails/SeriesPanel/SeriesPanel.js

Updates SUI to the latest.
Breaking changes:
- `Responsive` element is removed.
Followed the migration advice -> https://github.com/Semantic-Org/Semantic-UI-React/pull/4008

dependencies: Updates semantic-ui-react to latest

---

src/lib/api/ill/borrowingRequest.js
src/lib/config/defaultConfig.js
src/lib/modules/Location/LocationDatePicker.js
src/lib/pages/backoffice/DocumentRequest/DocumentRequestDetails/DocumentRequestActions/RejectAction.js
src/lib/pages/backoffice/DocumentRequest/DocumentRequestDetails/DocumentRequestHeader/DocumentRequestHeader.js
src/lib/pages/backoffice/DocumentRequest/DocumentRequestDetails/DocumentRequestMetadata/DocumentRequestMetadata.js
src/lib/pages/backoffice/DocumentRequest/DocumentRequestDetails/DocumentRequestSteps/DocumentRequestSteps.js
src/lib/pages/backoffice/DocumentRequest/DocumentRequestSearch/DocumentRequestListEntry.js
src/lib/pages/backoffice/Home/Home.js
src/lib/pages/backoffice/Home/lists/PendingILLPatronLoanExtensions/PendingILLPatronLoanExtensions.js
src/lib/pages/backoffice/Home/lists/PendingILLPatronLoanExtensions/index.js
src/lib/pages/backoffice/Home/lists/PendingILLPatronLoanExtensions/state/actions.js
src/lib/pages/backoffice/Home/lists/PendingILLPatronLoanExtensions/state/reducer.js
src/lib/pages/backoffice/Home/lists/index.js
src/lib/pages/backoffice/Home/reducer.js
src/lib/pages/backoffice/ILL/BorrowingRequest/BorrowingRequestDetails/BorrowingRequestPatronLoan/BorrowingRequestLoanExtension/BorrowingRequestLoanExtension.js
src/lib/pages/backoffice/ILL/BorrowingRequest/BorrowingRequestDetails/BorrowingRequestPatronLoan/BorrowingRequestPatronLoan.js
src/lib/store.js

* adds a search filter to immediately find pending extension requests
* adds a new home dashboard panel to show the pending extension requests
* fixed calendar for loans and extensions

ill: show patron loan extension status

---

src/lib/modules/Document/DocumentAuthors.js
src/lib/modules/Document/DocumentCard/DocumentCard.js
src/lib/modules/Document/DocumentInfo.js
src/lib/modules/Document/DocumentListEntry/DocumentListEntry.js
src/lib/modules/Document/DocumentListEntry/__snapshots__/DocumentListEntry.test.js.snap
src/lib/modules/Document/backoffice/DocumentList/DocumentListEntry.js
src/lib/modules/Items/backoffice/ItemListEntry.js
src/lib/modules/Loan/backoffice/LoanList/LoanListEntry.js
src/lib/pages/backoffice/Document/DocumentDetails/DocumentHeader.js
src/lib/pages/backoffice/Document/DocumentDetails/DocumentMetadata/DocumentMetadataGeneral.js
src/lib/pages/backoffice/Document/DocumentForms/DocumentEditor/DocumentForm/components/AuthorsField/AuthorSearchField.js
src/lib/pages/backoffice/EItem/EItemDetails/EItemHeader.js
src/lib/pages/backoffice/EItem/EItemSearch/EItemListEntry.js
src/lib/pages/backoffice/Item/ItemDetails/ItemHeader.js
src/lib/pages/backoffice/Loan/LoanDetails/LoanHeader/LoanHeader.js
src/lib/pages/frontsite/Documents/DocumentDetails/DocumentPanel/DocumentPanel.js
src/lib/pages/frontsite/Documents/DocumentDetails/DocumentPanel/DocumentPanelMobile.js
src/lib/pages/frontsite/PatronProfile/LoansListEntry.js
src/semantic-ui/site/elements/list.overrides

* Now we can show all authors in the details page
* Reduced overall displayed authors limit from 10 to 5
* closes https://github.com/CERNDocumentServer/cds-ils/issues/231
In terms of performance it's slightly slower when performing a search of 15 documents with 5k authors each. 
While a usual search takes around 400-450 ms, the heavy search takes 150-200 ms longer (550-600 ms).
----

authors: Improves authors display

---

src/lib/modules/Series/SeriesListEntry.js
src/lib/modules/Series/__snapshots__/SeriesListEntry.test.js.snap
src/lib/pages/backoffice/Document/DocumentDetails/DocumentMetadata/DocumentContents.js
src/lib/pages/backoffice/Series/SeriesDetails/SeriesContent/SeriesContent.js

Before in document details the keywords were not appearing if all the other content fields were empty and in series details the same happened with tags.
Fixes cover for series in list view.

backoffice: fix docs and series content tabs

---

src/lib/modules/Document/DocumentLinks.js
src/lib/modules/Literature/LiteratureAccessUrls.js

access urls: truncate url, add open access/login required text

---

src/lib/api/emails/email.js
src/lib/api/emails/index.js
src/lib/components/CancelModal/CancelModal.js
src/lib/components/CancelModal/__snapshots__/CancelModal.test.js.snap
src/lib/components/backoffice/ChangedBy/ChangedBy.js
src/lib/components/backoffice/buttons/ViewDetailsButtons/PatronDetailsLink.js
src/lib/modules/Document/DocumentCard/DocumentCard.js
src/lib/modules/Loan/backoffice/LoanList/LoanListEntry.js
src/lib/modules/Loan/backoffice/OverdueLoanSendMailModal/OverdueLoanSendMailModal.js
src/lib/modules/Loan/backoffice/OverdueLoanSendMailModal/index.js
src/lib/modules/Loan/backoffice/OverdueLoanSendMailModal/state/actions.js
src/lib/pages/backoffice/Acquisition/Order/OrderDetails/OrderLines.js
src/lib/pages/backoffice/Acquisition/Order/OrderSearch/OrderList/OrderListEntry.js
src/lib/pages/backoffice/DocumentRequest/DocumentRequestDetails/DocumentRequestHeader.js
src/lib/pages/backoffice/DocumentRequest/DocumentRequestSearch/DocumentRequestListEntry.js
src/lib/pages/backoffice/ILL/BorrowingRequest/BorrowingRequestDetails/BorrowingRequestMetadata.js
src/lib/pages/backoffice/ILL/BorrowingRequest/BorrowingRequestSearch/BorrowingRequestList/BorrowingRequestListEntry.js
src/lib/pages/backoffice/Loan/LoanDetails/Loan/Loan.js
src/lib/pages/backoffice/Loan/LoanDetails/LoanActionMenu/LoanActionMenu.js
src/lib/pages/backoffice/Loan/LoanDetails/LoanActions/LoanActions.js
src/lib/pages/backoffice/Loan/LoanDetails/LoanMetadata/LoanMetadata.js
src/semantic-ui/site/elements/button.overrides

Closes inveniosoftware/invenio-app-ils#523
- move actions in loan details to side
- make anonymous user unclickable (not in places where user with ongoing loans is displayed)
- in frontsite allow document cards to be opened in a new tab
- remove `send reminder` button from overview and loan search page
- add loading to `send reminder` button
Depends on inveniosoftware/invenio-app-ils#1037
Button:
Popup:
Loading:

[BLOCKED]backoffice: display number of overdue reminders in loan details

---

src/lib/modules/Series/SeriesInfo.js
src/lib/pages/backoffice/Loan/LoanDetails/LoanHeader/LoanHeader.js
src/lib/pages/backoffice/Series/SeriesDetails/SeriesContent/SeriesContent.js
src/lib/pages/backoffice/Series/SeriesDetails/SeriesPhysicalVolumes/SeriesPhysicalVolumes.js
src/lib/pages/backoffice/Series/SeriesDetails/SeriesPhysicalVolumes/index.js
src/lib/pages/backoffice/Series/SeriesEditor/schema.js
src/lib/pages/backoffice/Series/SeriesEditor/uiSchema.js
src/semantic-ui/site/globals/site.overrides

* Adds electronic_volumes_description and
physical_volumes_description fields to
series form and details page
* closes https://github.com/CERNDocumentServer/cds-ils/issues/361

journals: series fields

---

src/lib/api/series/series.js
src/lib/api/series/series.test.js
src/lib/config/common.js
src/lib/config/defaultConfig.js
src/lib/modules/Literature/LiteratureRelations.js
src/lib/modules/Relations/backoffice/components/RelationCard/SeriesCard.js
src/lib/modules/Relations/backoffice/components/RelationListEntry.js
src/lib/modules/Series/SeriesInfo.js
src/lib/modules/Series/SeriesTitle.js
src/lib/modules/Series/backoffice/SeriesSelectListEntry.js
src/lib/pages/backoffice/Series/SeriesDetails/SeriesHeader.js
src/lib/pages/backoffice/Series/SeriesDetails/SeriesMetadata/SeriesMetadata.js
src/lib/pages/backoffice/Series/SeriesEditor/schema.js
src/lib/pages/backoffice/Series/SeriesEditor/uiSchema.js
src/lib/pages/backoffice/Series/SeriesSearch/SeriesListEntry.js
src/lib/pages/frontsite/Series/SeriesDetails/SeriesPanel/SeriesPanel.js
src/lib/pages/frontsite/Series/SeriesDetails/SeriesPanel/SeriesPanelMobile.js

Closes https://github.com/inveniosoftware/invenio-app-ils/issues/1073
Depends on https://github.com/inveniosoftware/invenio-app-ils/pull/1075
- Moved language facets to the bottom

[BLOCKED]series: add facets and display series type

---

src/lib/modules/Document/DocumentCard/DocumentCard.js
src/lib/modules/Document/DocumentListEntry/DocumentListEntry.js
src/lib/modules/Document/DocumentListEntry/__snapshots__/DocumentListEntry.test.js.snap
src/lib/modules/Document/backoffice/DocumentList/DocumentListEntry.js
src/lib/modules/Literature/LiteratureTitle.js
src/lib/modules/Series/__snapshots__/SeriesCard.test.js.snap
src/lib/pages/backoffice/Document/DocumentDetails/DocumentHeader.js
src/lib/pages/backoffice/Document/DocumentDetails/DocumentRelations/RelationMultipartMonograph/RelationMultipartModal/RelationMultipartModal.js
src/lib/pages/backoffice/Loan/LoanDetails/LoanActionMenu/LoanActionMenu.js
src/lib/pages/backoffice/Patron/PatronDetails/PatronCurrentBorrowingRequests/__snapshots__/PatronCurrentBorrowingRequests.test.js.snap
src/lib/pages/backoffice/Patron/PatronDetails/PatronCurrentLoans/__snapshots__/PatronCurrentLoans.test.js.snap
src/lib/pages/backoffice/Patron/PatronDetails/PatronPastBorrowingRequests/__snapshots__/PatronPastBorrowingRequests.test.js.snap
src/lib/pages/backoffice/Patron/PatronDetails/PatronPendingLoans/__snapshots__/PatronPendingLoans.test.js.snap

Closes https://github.com/inveniosoftware/react-invenio-app-ils/issues/420
- fixes `send overdue reminder` button
Literature search card view
Literature search list view
Document details page frontsite (has been already implemented)
Series details page frontsite 
Document search backoffice
Document details page backoffice
Series details page backoffice (has been already implemented)

multipartRelations: display volume

---

src/lib/modules/Document/DocumentCard/DocumentCard.js
src/lib/modules/Document/backoffice/DocumentList/DocumentListEntry.js
src/lib/pages/frontsite/Documents/DocumentDetails/DocumentPanel/DocumentPanel.js
src/lib/pages/frontsite/Documents/DocumentDetails/DocumentPanel/DocumentPanelMobile.js

Add publication year and publisher to search and details pages of the documents.
closes https://github.com/CERNDocumentServer/cds-ils/issues/357
Backoffice list.
Frontsite search.
Frontsite inspect.

Document: add details to search and details view

---

src/lib/pages/backoffice/Loan/LoanDetails/LoanDetails.js
src/lib/pages/backoffice/Loan/LoanDetails/LoanOverbookedWarning/LoanOverbookedWarning.js
src/lib/pages/backoffice/Loan/LoanDetails/LoanOverbookedWarning/index.js

Show a warning in the loans of overbooked documents.
closes:  https://github.com/CERNDocumentServer/cds-ils/issues/523
Loan of an overbooked document.
Loan of a non overbooked document.

Show a warning for overbooked documents during check out

---

src/lib/pages/backoffice/Document/DocumentDetails/DocumentActionMenu/DocumentActionMenu.js
src/lib/pages/backoffice/Document/DocumentDetails/DocumentContent.js
src/lib/pages/backoffice/Document/DocumentDetails/DocumentDetails.js
src/lib/pages/backoffice/Document/DocumentDetails/DocumentPurchaseOrders/DocumentPurchaseOrders.js
src/lib/pages/backoffice/Document/DocumentDetails/DocumentPurchaseOrders/index.js

Create a new panel before statistics showing all the purchased orders of the current document.
closes https://github.com/CERNDocumentServer/cds-ils/issues/528

DocumentDetails: show purchase orders in document details

---

.prettierignore
src/lib/config/common.js
src/lib/config/defaultConfig.js
src/lib/pages/backoffice/Acquisition/Order/OrderEditor/schema.js
src/lib/pages/backoffice/Document/DocumentEditor/schema.js
src/lib/pages/backoffice/ILL/BorrowingRequest/BorrowingRequestEditor/schema.js
src/lib/pages/backoffice/Item/ItemEditor/schema.js
src/lib/pages/backoffice/Series/SeriesEditor/schema.js

Changes to acquisitions and borrowing forms:
- Sort status values in the purchase orders form, choosing the first value as the default one.
- Select Physical copy as the default value of the type in the borrowing requests form.
- Refactor code for displaying the fields in the dropdown selectors, adding an order field and the possibility of using a default value.
closes https://github.com/CERNDocumentServer/cds-ils/issues/327

Acquisition/borrowing: form fields display changes

---

src/lib/config/common.js

closes https://github.com/CERNDocumentServer/cds-ils/issues/591

Pending status is now the default for the ILL Borrowing request

---

src/lib/api/documentRequests/documentRequest.js
src/lib/pages/backoffice/Acquisition/Order/OrderDetails/OrderDocumentRequest.js
src/lib/pages/backoffice/Acquisition/Order/OrderDetails/OrderInformation.js

Show the related request literature if any in the purchase order details page.
closes https://github.com/CERNDocumentServer/cds-ils/issues/568
New purchase order with related literature request.
New purchase order without related literature request.
New purchase order with error fetching related literature request.
Old purchase order with related literature request.
Old purchase order without related literature request.

PurchaseOrderDetails: show related request literature

---

src/lib/modules/Document/DocumentCard/DocumentCard.js

BETTER added the title of the multipart_monograph to the documentCard because it can be more useful to the user than the volume only
closes https://github.com/CERNDocumentServer/cds-ils/issues/478

Document Card: multipart_monograph title

---

src/lib/modules/Relations/backoffice/components/RelationRemover/RelationRemover.js
src/lib/pages/backoffice/ILL/BorrowingRequest/BorrowingRequestDetails/BorrowingRequestPatronLoan/BorrowingRequestLoanExtension/BorrowingRequestLoanExtension.js
src/lib/pages/frontsite/PatronProfile/PatronCancelModal.js

Add a text to the document relation removal dialog indicating that deleting a relation would delete all other relations of that type to the document.
Replace the "No, take me back" and "Close" text in the modal's close buttons to "Cancel".
closes: https://github.com/CERNDocumentServer/cds-ils/issues/547
New design.
First design.

record relations: show warning message when deleting a relation

---

src/lib/config/defaultConfig.js
src/lib/forms/rjsf/RJSForm.js
src/lib/pages/backoffice/DocumentRequest/DocumentRequestEditor/DocumentRequestEditor.js
src/lib/pages/backoffice/DocumentRequest/DocumentRequestEditor/schema.js
src/lib/pages/backoffice/DocumentRequest/DocumentRequestEditor/uiSchema.js

FIX the document request form was not holding its state after an error from the api and thus was confusing to the user, lastly also moved the request type next to the state field as it is a required field and easy to miss at the bottom.
closes https://github.com/CERNDocumentServer/cds-ils/issues/584

DocumentRequest: form state fix

---

src/lib/components/ResultsTable/ResultsTable.js
src/lib/components/ResultsTable/ResultsTableFooter.js
src/lib/components/ResultsTable/__snapshots__/ResultsTable.test.js.snap
src/lib/index.js
src/lib/pages/backoffice/Acquisition/Order/OrderSearch/__snapshots__/OrderSearch.test.js.snap
src/lib/pages/backoffice/Document/DocumentDetails/DocumentItems/__snapshots__/DocumentItems.test.js.snap
src/lib/pages/backoffice/Document/DocumentDetails/DocumentPendingLoans/__snapshots__/DocumentPendingLoans.test.js.snap
src/lib/pages/backoffice/Document/DocumentSearch/__snapshots__/DocumentSearch.test.js.snap
src/lib/pages/backoffice/DocumentRequest/DocumentRequestSearch/__snapshots__/DocumentRequestSearch.test.js.snap
src/lib/pages/backoffice/EItem/EItemDetails/EItemFiles/__snapshots__/EItemFiles.test.js.snap
src/lib/pages/backoffice/EItem/EItemSearch/__snapshots__/EItemSearch.test.js.snap
src/lib/pages/backoffice/Item/ItemDetails/ItemPastLoans/__snapshots__/ItemPastLoans.test.js.snap
src/lib/pages/backoffice/Item/ItemDetails/ItemPendingLoans/__snapshots__/ItemPendingLoans.test.js.snap
src/lib/pages/backoffice/Item/ItemSearch/__snapshots__/ItemSearch.test.js.snap
src/lib/pages/backoffice/Loan/LoanSearch/__snapshots__/LoanSearch.test.js.snap
src/lib/pages/backoffice/Patron/PatronDetails/PatronCurrentBorrowingRequests/__snapshots__/PatronCurrentBorrowingRequests.test.js.snap
src/lib/pages/backoffice/Patron/PatronDetails/PatronCurrentLoans/__snapshots__/PatronCurrentLoans.test.js.snap
src/lib/pages/backoffice/Patron/PatronDetails/PatronDocumentRequests/__snapshots__/PatronDocumentRequests.test.js.snap
src/lib/pages/backoffice/Patron/PatronDetails/PatronPastBorrowingRequests/__snapshots__/PatronPastBorrowingRequests.test.js.snap
src/lib/pages/backoffice/Patron/PatronDetails/PatronPendingLoans/__snapshots__/PatronPendingLoans.test.js.snap
src/lib/pages/backoffice/Patron/PatronSearch/__snapshots__/PatronSearch.test.js.snap
src/lib/pages/backoffice/Providers/ProviderSearch/__snapshots__/ProviderSearch.test.js.snap
src/lib/pages/backoffice/Series/SeriesDetails/SeriesDocuments/__snapshots__/SeriesDocuments.test.js.snap
src/lib/pages/backoffice/Series/SeriesSearch/__snapshots__/SeriesSearch.test.js.snap

Active page now works.
Allow hiding the text of the footer of the table.

RecordsTable: Use activePage to render desired rows.

---

src/lib/forms/rjsf/widgets/RJSFVocabulary.js

Now validates if the value passed to a vocabulary field is a valid option of that vocabulary
closes https://github.com/CERNDocumentServer/cds-ils/issues/653

RJSFVocabulary: validate value

---

src/lib/api/loans/loan.js
src/lib/modules/Loan/actions.js
src/lib/pages/backoffice/Document/DocumentDetails/DocumentPendingLoans/state/actions.js
src/lib/pages/backoffice/Document/DocumentDetails/DocumentPendingLoans/state/actions.test.js

Loan already requested modal added to the rest of loans.
closes: https://github.com/CERNDocumentServer/cds-ils/issues/664
implements https://github.com/inveniosoftware/react-invenio-app-ils/pull/507
Now the modal appears for the second loan (and not the first). Hovering in the link of the modal we can see it Links correctly to the first loan.

Loans: loan already requested modal removed from first loan.

---

src/lib/pages/backoffice/Patron/PatronDetails/PatronPastLoans/PatronPastLoans.js

closes: https://github.com/CERNDocumentServer/cds-ils/issues/638

PatronPastLoans: fix wrong query in 'see all' loans history

---

src/lib/components/CancelModal/CancelModal.js
src/lib/components/CancelModal/__snapshots__/CancelModal.test.js.snap
src/lib/components/Error/Error.js
src/lib/components/Notifications/actions.js
src/lib/modules/Loan/actions.js
src/lib/pages/backoffice/Actions/CheckIn/ItemsSearch/state/actions.js
src/lib/pages/backoffice/Actions/CheckOut/state/actions.js
src/lib/pages/backoffice/Loan/LoanDetails/LoanActions/CancelButton.js
src/lib/pages/backoffice/Loan/LoanDetails/LoanActions/ExtendModal/ExtendModal.js
src/lib/pages/backoffice/Loan/LoanDetails/LoanActions/ExtendModal/index.js
src/lib/pages/backoffice/Loan/LoanDetails/LoanActions/LoanActions.js

Fix the cancel modal of loan actions.
closes: CERNDocumentServer/cds-ils#663
re-implements: https://github.com/inveniosoftware/react-invenio-app-ils/pull/508
Modal:
After successfully pressing extend:
After unsuccessfully pressing extend:

LoanActions: warn the users that extend an overbooked loan.

---

src/lib/forms/rjsf/RJSForm.js

Now disables the onEnter event on RJSF inputs because it was causing some odd behaviour with empty fields spawning out of nowhere when pressing enter.
closes https://github.com/CERNDocumentServer/cds-ils/issues/673

RSJF: Fix bug on enter press

---

src/lib/modules/Document/DocumentAlternativeAbstracts.js
src/lib/pages/backoffice/Document/DocumentDetails/DocumentMetadata/DocumentContents.js
src/lib/pages/backoffice/Document/DocumentDetails/DocumentMetadata/DocumentMetadataGeneral.js

backoffice: Add alternative titles to details page

---

src/lib/modules/Document/DocumentCard/DocumentCard.js
src/lib/modules/Relations/backoffice/components/RelationCard/SeriesCard.js

* add missing covering component to multipart and serials attaching modals
* fix overridable component name
* closes https://github.com/inveniosoftware/react-invenio-app-ils/issues/424
Covers appearing preview:

attach multipart modal: fix cover image appearing

---

src/lib/components/SearchBar/SearchBarILS.js
src/lib/components/SearchBar/__snapshots__/SearchBarILS.test.js.snap
src/lib/modules/Series/SeriesLiteratureSearch/SeriesLiteratureSearch.js
src/lib/modules/Series/SeriesLiteratureSearch/__snapshots__/SeriesLiteratureSearch.test.js.snap
src/lib/pages/frontsite/Documents/DocumentDetails/DocumentDetails.js
src/lib/pages/frontsite/Home/Headline/HomeSearchBar.js
src/lib/pages/frontsite/Literature/LiteratureSearch/LiteratureSearch.js
src/lib/pages/frontsite/Series/SeriesDetails/SeriesDetails.js

* improve series search tip popup
* remove autofocus on series details searchbar
* remove autofocus from all searchbars in mobile view
* cleanup the ResultsLoader
* closes https://github.com/inveniosoftware/react-invenio-app-ils/issues/549
Search tip and autofocus preview:

improve series search tip popup, fix searchbar autofocus

---

src/lib/pages/frontsite/Documents/DocumentDetails/DocumentPanel/DocumentTitle.js

#Closes: https://github.com/CERNDocumentServer/cds-ils/issues/830
Before:
After:

frontsite: Show Edition and Publication year on Literature page

---

src/lib/pages/frontsite/Documents/DocumentDetails/DocumentPanel/DocumentTitle.js

Closes: https://github.com/CERNDocumentServer/cds-ils/issues/734
Desktop:
Mobile:

frontsite: DocumentDetails: Display volume number near title

---

CHANGES.md
package-lock.json
package.json
src/lib/pages/backoffice/Patron/PatronDetails/ItemsSearch/ItemsSearch.js

Disable enter key in paste handler so that when a paste happens and enter is pressed at the same time, both the onPasteHandler and onSearchHandler should not get triggered in parallel.

backoffice: PatronDetails: Disable enter key in paste event handler

---

src/lib/api/documents/document.js
src/lib/modules/Document/DocumentSubjectLayout.js
src/lib/modules/Document/DocumentSubjectSearch.js
src/lib/pages/frontsite/Documents/DocumentDetails/DocumentDetails.js

Resolves: https://github.com/CERNDocumentServer/cds-ils/issues/832

frontsite: DocumentDetails: Add section for documents with same subjects

---

src/lib/pages/frontsite/Documents/DocumentDetails/DocumentPanel/DocumentTitle.js
src/semantic-ui/site/globals/site.overrides

closes: https://github.com/CERNDocumentServer/cds-ils/issues/734

frontsite: DocumentDetails: Display multipart above Literature Title

---

src/lib/pages/backoffice/Home/Home.js
src/lib/pages/backoffice/ILL/BorrowingRequest/BorrowingRequestSearch/BorrowingRequestList/BorrowingRequestListEntry.js
src/lib/pages/backoffice/Providers/ProviderSearch/ProviderListEntry.js

ui: improve screen adaptability
