inveniosoftware/react-invenio-app-ils

src/lib/api/base.js
src/lib/api/ill/borrowingRequest.js
src/lib/config/invenioConfig.js
src/lib/pages/backoffice/ILL/BorrowingRequest/BorrowingRequestDetails/BorrowingRequestPatronLoan/BorrowingRequestLoanExtension/BorrowingRequestLoanExtension.js
src/lib/pages/backoffice/ILL/BorrowingRequest/BorrowingRequestDetails/BorrowingRequestPatronLoan/BorrowingRequestLoanExtension/actions.js
src/lib/pages/backoffice/ILL/BorrowingRequest/BorrowingRequestDetails/BorrowingRequestPatronLoan/BorrowingRequestLoanExtension/index.js
src/lib/pages/backoffice/ILL/BorrowingRequest/BorrowingRequestDetails/BorrowingRequestPatronLoan/BorrowingRequestLoanExtension/reducer.js
src/lib/pages/backoffice/ILL/BorrowingRequest/BorrowingRequestDetails/BorrowingRequestPatronLoan/BorrowingRequestPatronLoan.js
src/lib/store.js

backoffice: ill accept/decline extension

---

src/lib/modules/ESSelector/ESSelector.js
src/lib/pages/backoffice/Document/DocumentForms/DocumentEditor/DocumentForm/DocumentForm.js
src/lib/pages/backoffice/DocumentRequest/DocumentRequestDetails/DocumentRequestSteps/DocumentStep/DocumentStep.js
src/lib/pages/backoffice/DocumentRequest/DocumentRequestDetails/DocumentRequestSteps/DocumentStep/index.js
src/lib/pages/backoffice/DocumentRequest/DocumentRequestDetails/DocumentRequestSteps/ProviderStep/ProviderStep.js
src/lib/pages/backoffice/DocumentRequest/DocumentRequestDetails/DocumentRequestSteps/ProviderStep/index.js
src/lib/pages/backoffice/DocumentRequest/DocumentRequestDetails/DocumentRequestSteps/ReviewStep/ReviewStep.js
src/lib/pages/backoffice/DocumentRequest/DocumentRequestDetails/DocumentRequestSteps/ReviewStep/index.js
src/lib/pages/backoffice/DocumentRequest/DocumentRequestDetails/DocumentRequestSteps/StepsActions/StepsActions.js
src/lib/pages/backoffice/DocumentRequest/DocumentRequestDetails/DocumentRequestSteps/StepsActions/index.js
src/lib/pages/backoffice/DocumentRequest/DocumentRequestDetails/state/actions.js
src/lib/pages/backoffice/ILL/BorrowingRequest/BorrowingRequestEditor/BorrowingRequestEditor.js

ill: create borrowing request from document request

---

src/lib/components/CancelModal/CancelModal.js
src/lib/components/CancelModal/__snapshots__/CancelModal.test.js.snap
src/lib/modules/ESSelector/serializer.js
src/lib/modules/Loan/actions.js
src/lib/pages/backoffice/DocumentRequest/DocumentRequestDetails/DocumentRequestSteps/StepsActions/StepsActions.js
src/lib/pages/backoffice/DocumentRequest/DocumentRequestDetails/state/actions.js
src/lib/pages/backoffice/ILL/BorrowingRequest/BorrowingRequestEditor/BorrowingRequestForm/BorrowingRequestForm.js
src/lib/pages/backoffice/Loan/LoanDetails/LoanActions/LoanActions.js
src/lib/pages/backoffice/Loan/LoanDetails/LoanActions/index.js
src/lib/pages/frontsite/PatronProfile/PatronPastDocumentRequests/PatronPastDocumentRequests.js

to review: last 2 commits
closes: #73

UI bugfixing

---

src/lib/components/backoffice/Sidebar/Sidebar.js
src/lib/pages/frontsite/Home/Sections/SectionInstallation.js
src/lib/pages/frontsite/Home/Sections/SectionServices.js
src/lib/pages/frontsite/Home/Sections/SectionsWrapper.js
src/semantic-ui/site/elements/list.overrides
src/semantic-ui/site/views/card.overrides

Homepage: Add installation instructions section

---

src/lib/api/acquisition/order.js
src/lib/pages/backoffice/DocumentRequest/DocumentRequestDetails/DocumentRequestSteps/ProviderStep/ProviderStep.js

- can select only Acquisition Orders with PENDING status
- can select only ILL Loans with PENDING status 
- closes #76

bug: broken state for new literature requests

---

src/lib/pages/backoffice/EItem/EItemDetails/File/index.js
src/lib/pages/backoffice/EItem/EItemDetails/File/reducer.js
src/lib/pages/backoffice/EItem/EItemDetails/File/state/actions.js
src/lib/pages/backoffice/EItem/EItemDetails/File/state/reducer.js
src/lib/store.js

* Adds file reducer to store
* Reloads e-item detail page
after uploading file
* closes #10

eitems: Fixes upload file

---

src/lib/config/invenioConfig.js
src/lib/forms/core/SelectField.js
src/lib/forms/core/StringField.js
src/lib/forms/core/VocabularyField.js
src/lib/pages/backoffice/DocumentRequest/DocumentRequestDetails/DocumentRequestMetadata/DocumentRequestMetadata.js
src/lib/pages/frontsite/DocumentRequests/DocumentRequestForm.js
src/lib/pages/frontsite/Literature/LiteratureSearch/SearchMessage/SearchMessage.js
src/lib/pages/frontsite/PatronProfile/PatronCurrentDocumentRequests/PatronCurrentDocumentRequests.js

* adds medium field to frontsite
profile page and backoffice
* adds new dropdown to the
request document form 
* closes #99 
--------------------------------
--------------------------------

docreq: add medium field

---

src/lib/config/invenioConfig.js
src/lib/forms/core/StringField.js
src/lib/pages/backoffice/DocumentRequest/DocumentRequestDetails/DocumentRequestMetadata/DocumentRequestMetadata.js
src/lib/pages/frontsite/DocumentRequests/DocumentRequestForm.js
src/lib/pages/frontsite/PatronProfile/PatronCurrentDocumentRequests/PatronCurrentDocumentRequests.js

* Adds request type field to frontsite
profile page and backoffice
* Adds 2 new dropdown and a string field
to the request document form
* Adds payment method and payment
information to backoffice
---------
---------

docreq: Adds request type field

---

src/lib/modules/Loan/backoffice/LoanList/LoanListEntry.js
src/lib/pages/backoffice/Document/DocumentDetails/state/actions.js
src/lib/pages/backoffice/Loan/LoanDetails/LoanMetadata/LoanMetadata.js

Overridable components for this: https://github.com/CERNDocumentServer/cds-books/pull/117

Backoffice: make components overridable for delivery method icon

---

src/lib/pages/backoffice/Item/ItemDetails/state/actions.js

ItemDetails: fix bug in checkout

---

src/lib/index.js
src/lib/pages/frontsite/DocumentRequests/DocumentRequestForm.js

* Adds overridable document request form

docreq: Adds overridable form

---

src/lib/modules/Series/SeriesTitle.js
src/lib/pages/frontsite/Documents/DocumentDetails/DocumentPanel/DocumentTitle.js
src/lib/pages/frontsite/Series/SeriesDetails/SeriesPanel/SeriesPanel.js
src/semantic-ui/site/elements/header.overrides
src/semantic-ui/site/elements/list.overrides

* if a subtitle is available for a document or series it is displayed below the main title
* the margin between the title and the author was suppressed
* closes CERNDocumentServer/cds-books#111

document: display subtitle

---

src/lib/pages/backoffice/Loan/LoanDetails/AvailableItems/AvailableItems.js
src/lib/pages/backoffice/Loan/LoanDetails/AvailableItems/index.js

backoffice: add loading state to loan checkout

---

src/lib/config/defaultConfig.js
src/lib/forms/core/SelectField.js
src/lib/pages/backoffice/Document/DocumentForms/DocumentEditor/DocumentForm/DocumentForm.js
src/lib/pages/backoffice/Patron/PatronDetails/ItemsSearch/ItemsResultsList/ItemsResultsList.js
src/lib/pages/frontsite/Series/SeriesDetails/SeriesMetadata/SeriesMetadata.js
src/lib/pages/frontsite/Series/SeriesDetails/SeriesPanel/SeriesPanel.js

* closes #43
* closes #107
* closes #110
* closes #124
* closes #125

global: minor fixes

---

src/lib/pages/backoffice/EItem/EItemDetails/EItemMetadata/EItemMetadata.js
src/lib/pages/backoffice/EItem/EItemForms/EItemEditor/EItemForm/EItemForm.js

* new field in create/update form
* identifiers appear in the metadata detail panel
* requires inveniosoftware/invenio-app-ils#914
* closes inveniosoftware/invenio-app-ils#658

backoffice: add identifiers to e-items

---

package.json
src/lib/api/base.js

- addresses https://github.com/inveniosoftware/invenio-app-ils/issues/867

global: CSRF support

---

src/lib/api/base.js
src/lib/api/users/user.js
src/lib/authentication/services/AuthenticationService.js
src/lib/authentication/state/actions.js
src/lib/authentication/state/actions.test.js
src/lib/pages/frontsite/Documents/DocumentDetails/DocumentCirculation/DocumentCirculation.js
src/lib/pages/frontsite/Documents/DocumentDetails/DocumentCirculation/LoanAvailability.js
src/lib/pages/frontsite/Documents/DocumentDetails/DocumentCirculation/LoanInformationBullets.js
src/lib/pages/frontsite/Documents/DocumentDetails/DocumentCirculation/actions.js
src/lib/pages/frontsite/Documents/DocumentDetails/DocumentCirculation/index.js
src/lib/pages/frontsite/Documents/DocumentDetails/DocumentCirculation/reducer.js
src/lib/pages/frontsite/Documents/DocumentDetails/DocumentDetails.js
src/lib/pages/frontsite/Documents/DocumentDetails/LoanRequestForm/LoanRequestForm.js
src/lib/pages/frontsite/Documents/DocumentDetails/LoanRequestForm/LoanRequestForm.test.js
src/lib/pages/frontsite/Documents/DocumentDetails/LoanRequestForm/__snapshots__/LoanRequestForm.test.js.snap
src/lib/store.js

* depends on inveniosoftware/invenio-app-ils#915
* add two new states to the loan request form
* closes #116

[depends on: invenio-app-ils#915] frontsite: add states to loan request

---

src/lib/config/common.js
src/lib/config/defaultConfig.js
src/lib/forms/core/SelectField.js

- added missing options for document type
- options are required

forms: fix options for select field

---

src/lib/pages/backoffice/Patron/PatronDetails/ItemsSearch/ItemsResultsList/ItemsResultsList.js

PatronDetails: disable force checkout for items on loan

---

src/lib/pages/backoffice/Item/ItemDetails/ItemPendingLoans/ItemPendingLoans.js
src/lib/pages/backoffice/Loan/LoanDetails/AvailableItems/AvailableItems.js

* Adds the option to scan a copy
to filter the available physical
copies list
* closes #44
-----------------------------
-----------------------------

loanreq: checkout by scan

---

src/semantic-ui/site/collections/table.overrides

Datepicker: fix mobile view

---

src/lib/forms/components/UrlsField.js
src/lib/forms/core/ArrayField.js
src/lib/forms/core/BaseForm/BaseForm.js
src/lib/forms/core/BaseForm/RecordSerializer.js
src/lib/forms/core/BaseForm/RecordSerializer.test.js
src/lib/forms/core/DateTimeFields/DateInputField.js
src/lib/forms/core/ObjectListField.js
src/lib/forms/core/PriceField.js
src/lib/forms/core/SelectField.js
src/lib/forms/core/StringField.js
src/lib/forms/core/SubForm.js
src/lib/pages/backoffice/Acquisition/Order/OrderEditor/OrderEditor.js
src/lib/pages/backoffice/Acquisition/Order/OrderEditor/OrderForm/OrderForm.js
src/lib/pages/backoffice/Acquisition/Order/OrderEditor/OrderForm/OrderLines.js
src/lib/pages/backoffice/Document/DocumentForms/DocumentEditor/DocumentForm/DocumentForm.js
src/lib/pages/backoffice/Document/DocumentForms/DocumentEditor/DocumentForm/components/AlternativeTitles.js
src/lib/pages/backoffice/Document/DocumentForms/DocumentEditor/DocumentForm/components/AuthorsField/AuthorsField.js
src/lib/pages/backoffice/Document/DocumentForms/DocumentEditor/DocumentForm/components/Identifiers.js
src/lib/pages/backoffice/EItem/EItemForms/EItemEditor/EItemForm/eitemSubmitSerializer.js
src/lib/pages/backoffice/ILL/BorrowingRequest/BorrowingRequestEditor/BorrowingRequestForm/BorrowingRequestForm.js
src/lib/pages/backoffice/Item/ItemForms/ItemEditor/ItemEditor.js
src/lib/pages/backoffice/Item/ItemForms/ItemEditor/ItemForm/ItemForm.js
src/lib/pages/backoffice/Location/LocationForms/InternalLocationEditor/components/InternalLocationForm/InternalLocationForm.js
src/lib/pages/backoffice/Series/SeriesForms/SeriesEditor/SeriesEditor.js
src/lib/pages/backoffice/Series/SeriesForms/SeriesEditor/components/SeriesForm/AccessUrls.js

* Fixes input errors on the fields
* Fixes bugs that caused errors
when opening forms
* Fixes bug that caused the creation
of 2 vendors
* Fixes bugs that caused error when
submitting forms
* Fixes some more minor bugs
* closes #74
* closes #26

forms: Fixes form bugs

---

src/lib/forms/components/IdentifiersField.js
src/lib/forms/components/UrlsField.js
src/lib/forms/core/ArrayField.js
src/lib/forms/core/BooleanField.js
src/lib/forms/core/ObjectListField.js
src/lib/pages/backoffice/Document/DocumentForms/DocumentEditor/DocumentEditor.js
src/lib/pages/backoffice/Document/DocumentForms/DocumentEditor/DocumentForm/DocumentAdditionalInfo.js
src/lib/pages/backoffice/Document/DocumentForms/DocumentEditor/DocumentForm/DocumentBasicMetadata.js
src/lib/pages/backoffice/Document/DocumentForms/DocumentEditor/DocumentForm/DocumentContent.js
src/lib/pages/backoffice/Document/DocumentForms/DocumentEditor/DocumentForm/DocumentCurationCatalog.js
src/lib/pages/backoffice/Document/DocumentForms/DocumentEditor/DocumentForm/DocumentForm.js
src/lib/pages/backoffice/Document/DocumentForms/DocumentEditor/DocumentForm/DocumentLicensesCopyright.js
src/lib/pages/backoffice/Document/DocumentForms/DocumentEditor/DocumentForm/DocumentPublishing.js
src/lib/pages/backoffice/Document/DocumentForms/DocumentEditor/DocumentForm/components/AlternativeTitles.js
src/lib/pages/backoffice/Document/DocumentForms/DocumentEditor/DocumentForm/components/AuthorsField/AuthorForm.js
src/lib/pages/backoffice/Document/DocumentForms/DocumentEditor/DocumentForm/components/AuthorsField/AuthorSearchField.js
src/lib/pages/backoffice/Document/DocumentForms/DocumentEditor/DocumentForm/components/AuthorsField/AuthorsField.js
src/lib/pages/backoffice/Document/DocumentForms/DocumentEditor/DocumentForm/components/Copyrights.js
src/lib/pages/backoffice/Document/DocumentForms/DocumentEditor/DocumentForm/components/Identifiers.js
src/lib/pages/backoffice/Document/DocumentForms/DocumentEditor/DocumentForm/components/Keywords.js
src/lib/pages/backoffice/Document/DocumentForms/DocumentEditor/DocumentForm/components/TableOfContent.js
src/lib/pages/backoffice/Document/DocumentForms/DocumentEditor/DocumentForm/components/TagsField/TagsField.js
src/lib/pages/backoffice/Series/SeriesForms/SeriesEditor/components/SeriesForm/AccessUrls.js
src/lib/pages/backoffice/Series/SeriesForms/SeriesEditor/components/SeriesForm/SeriesForm.js

* Reorganise the fields
* closes #154

Fix document form

---

src/lib/pages/backoffice/Series/SeriesForms/SeriesEditor/components/SeriesForm/SeriesForm.js

SeriesForm: reorganize fields

---

src/lib/forms/core/AccordionField.js

form: fix AccordionField style

---

src/lib/pages/backoffice/Item/ItemForms/ItemEditor/ItemForm/ItemForm.js

ItemForm: reorganize fields

---

src/lib/pages/backoffice/Acquisition/Vendor/VendorEditor/VendorForm/VendorForm.js
src/lib/pages/backoffice/ILL/Library/LibraryEditor/LibraryForm/LibraryForm.js
src/lib/pages/backoffice/Location/LocationForms/InternalLocationEditor/components/InternalLocationForm/InternalLocationForm.js
src/lib/pages/backoffice/Location/LocationForms/LocationEditor/components/LocationForm/LocationForm.js

* Reorganize vendor form, library form,
lcation form and internal location form
* closes #163

forms: Reorganize fields

---

src/lib/pages/backoffice/EItem/EItemForms/EItemEditor/EItemForm/EItemForm.js

eitemForms: Reorganize fields

---

src/lib/pages/backoffice/ILL/BorrowingRequest/BorrowingRequestEditor/BorrowingRequestForm/BorrowingRequestForm.js
src/lib/pages/backoffice/ILL/BorrowingRequest/BorrowingRequestEditor/BorrowingRequestForm/OrderInfo.js
src/lib/pages/backoffice/ILL/BorrowingRequest/BorrowingRequestEditor/BorrowingRequestForm/Payment.js

 borrowingRequestForm: Reorganize fields

---

src/lib/pages/backoffice/Acquisition/Order/OrderEditor/OrderForm/OrderForm.js
src/lib/pages/backoffice/Acquisition/Order/OrderEditor/OrderForm/OrderInfo.js
src/lib/pages/backoffice/Acquisition/Order/OrderEditor/OrderForm/OrderLines.js
src/lib/pages/backoffice/Acquisition/Order/OrderEditor/OrderForm/Payment.js

OrderForm: reorganize fields

---

package.json

addresses inveniosoftware/invenio-app-ils#867

global: npm start runs on HTTPS by default

---

src/lib/modules/Document/DocumentInfo.js
src/lib/modules/Document/DocumentLanguages.js
src/lib/modules/Document/DocumentListEntry/DocumentListEntry.js
src/lib/modules/Document/DocumentListEntry/__snapshots__/DocumentListEntry.test.js.snap
src/lib/modules/Document/backoffice/DocumentList/DocumentListEntry.js
src/lib/modules/Literature/LiteratureKeywords.js
src/lib/modules/Literature/LiteratureTags.js
src/lib/modules/Relations/backoffice/components/MultipleSelections/MultipleSelections.js
src/lib/modules/Relations/backoffice/components/RelationSummary/RelationSummary.js
src/lib/modules/Series/SeriesInfo.js
src/lib/pages/backoffice/Document/DocumentDetails/DocumentHeader.js
src/lib/pages/backoffice/Document/DocumentDetails/DocumentMetadata/DocumentMetadataGeneral.js
src/lib/pages/backoffice/Document/DocumentDetails/DocumentRelations/RelationLanguages/RelationLanguages.js
src/lib/pages/backoffice/Document/DocumentDetails/DocumentRelations/RelationLanguages/RelationLanguagesModal/RelationLanguagesModal.js
src/lib/pages/backoffice/Document/DocumentDetails/DocumentRelations/RelationOther/RelationOtherModal/RelationOtherModal.js
src/lib/pages/backoffice/Series/SeriesDetails/SeriesHeader.js
src/lib/pages/backoffice/Series/SeriesDetails/SeriesMetadata/SeriesMetadata.js
src/lib/pages/backoffice/Series/SeriesForms/SeriesEditor/components/SeriesForm/SeriesForm.js
src/lib/pages/backoffice/Series/SeriesSearch/SeriesListEntry.js
src/lib/pages/frontsite/Documents/DocumentDetails/DocumentDetails.js
src/lib/pages/frontsite/Documents/DocumentDetails/DocumentPanel/DocumentPanelMobile.js
src/lib/pages/frontsite/Series/SeriesDetails/SeriesDetails.js
src/lib/pages/frontsite/Series/SeriesDetails/SeriesPanel/SeriesPanelMobile.js

* covers frontsite & backoffice
* refactored code into components
* depends on inveniosoftware/invenio-app-ils#930
* closes inveniosoftware/invenio-app-ils#917

Add keywords and tags to series

---

src/lib/api/loans/loan.js
src/lib/pages/backoffice/Loan/LoanDetails/LoanActionMenu/LoanActionMenu.js
src/lib/pages/backoffice/Loan/LoanDetails/LoanDetails.js
src/lib/pages/backoffice/Loan/LoanDetails/LoanUpdateDates/LoanUpdateDates.js
src/lib/pages/backoffice/Loan/LoanDetails/LoanUpdateDates/index.js
src/lib/pages/backoffice/Loan/LoanDetails/LoanUpdateDates/reducer.js
src/lib/pages/backoffice/Loan/LoanDetails/LoanUpdateDates/state/actions.js
src/lib/pages/backoffice/Loan/LoanDetails/LoanUpdateDates/state/reducer.js
src/lib/store.js

* adds a new button to modify the dates of loan, which opens a simple modal
* depends on inveniosoftware/invenio-app-ils#933
* closes #84

[depends on invenio-app-ils#933] Backoffice: loan editable dates

---

src/lib/forms/core/SelectField.js
src/lib/pages/backoffice/Document/DocumentForms/DocumentEditor/DocumentForm/components/LicensesField.js

* depends on inveniosoftware/invenio-app-ils#935
* closes inveniosoftware/invenio-app-ils#916

[depends on invenio-app-ils#935] Backoffice: update license field

---

src/lib/authentication/components/LoginWithOauthButton/LoginWithOauthButton.js
src/lib/authentication/pages/Login/Login.js
src/lib/authentication/pages/Login/LoginWithLocalAccount/LoginWithLocalAccount.js
src/lib/authentication/pages/Login/LoginWithLocalAccount/index.js
src/lib/authentication/pages/Login/LoginWithOauthProviders/LoginWithOauthProviders.js
src/lib/authentication/pages/Login/LoginWithOauthProviders/index.js
src/lib/authentication/pages/Login/index.js

* Deletes the notifications with the error
messages and displays this messages in
a box.
* closes #145
------------------

 fronsite: Updates error message in login page

---

src/lib/modules/Document/DocumentInfo.js
src/lib/modules/Series/SeriesInfo.js

global: remove hardcoded vocabulary values

---

src/lib/modules/Literature/LiteratureTitle.js
src/lib/modules/Loan/backoffice/OverdueLoanSendMailModal/OverdueLoanSendMailModal.js
src/lib/pages/backoffice/Patron/PatronDetails/PatronCurrentBorrowingRequests/__snapshots__/PatronCurrentBorrowingRequests.test.js.snap
src/lib/pages/backoffice/Patron/PatronDetails/PatronPastBorrowingRequests/__snapshots__/PatronPastBorrowingRequests.test.js.snap
src/lib/pages/backoffice/Patron/PatronDetails/PatronPendingLoans/__snapshots__/PatronPendingLoans.test.js.snap
src/semantic-ui/site/globals/site.overrides

Backoffice: Adds inormation to overdue reminder

---

src/lib/components/SearchBar/SearchBar.js
src/lib/components/SearchBar/__snapshots__/SearchBar.test.js.snap
src/lib/pages/backoffice/Patron/PatronDetails/ItemsSearch/ItemsResultsList/ItemsResultsList.js
src/lib/pages/backoffice/Patron/PatronDetails/ItemsSearch/ItemsSearch.js
src/lib/pages/backoffice/Patron/PatronDetails/ItemsSearch/index.js
src/lib/store.js

* Removes misleading box
* Now it cleans the results when
leaving the page
* Fixes bug that prevents from searching
by pressing enter
* Adds a loading state for the search
* closes #79

Backoffice: Fixes patron page checkout

---

src/lib/forms/core/ObjectListField.js
src/lib/pages/backoffice/Document/DocumentForms/DocumentEditor/DocumentForm/components/AuthorsField/AuthorsField.js

* Adds an error message if there are no authors
saved
* Fixes some minor visual bugs in the authors
field
* closes #27

backoffice: Fixes authors field in documents

---

src/lib/modules/Document/DocumentInfo.js
src/lib/modules/Document/DocumentPublicationInfo.js
src/lib/modules/Document/DocumentStats.js
src/lib/modules/SearchControls/SearchControls.js
src/lib/modules/SearchControls/__snapshots__/SearchControls.test.js.snap
src/lib/pages/backoffice/Document/DocumentForms/DocumentEditor/DocumentForm/components/PublicationInfoField.js
src/lib/pages/frontsite/Documents/DocumentDetails/DocumentCirculation/DocumentEItems.js
src/lib/pages/frontsite/Documents/DocumentDetails/DocumentDetails.js
src/lib/pages/frontsite/Documents/DocumentDetails/DocumentMetadata/DocumentMetadata.js
src/lib/pages/frontsite/Documents/DocumentDetails/DocumentMetadata/DocumentMetadataTabs/DocumentMetadataTabs.js
src/semantic-ui/site/collections/message.overrides
src/semantic-ui/site/collections/table.overrides
src/semantic-ui/site/elements/list.overrides
src/semantic-ui/site/views/card.overrides

frontsite: publication information

---

src/lib/config/defaultConfig.js
src/lib/pages/backoffice/Item/ItemDetails/ItemCirculation/ItemCirculation.js
src/lib/pages/backoffice/Item/ItemDetails/ItemHeader.js
src/semantic-ui/site/elements/label.overrides

ItemDetails: move circulation label to title

---

src/lib/modules/SearchControls/SearchControlsOverrides.js
src/lib/modules/SearchControls/SearchEmptyResults.js
src/lib/modules/SearchControls/SearchError.js
src/lib/modules/SearchControls/SearchMessage.js
src/semantic-ui/site/elements/header.overrides

* also displays a better component on any other search-related error (override was not registered correctly)
* closes inveniosoftware/invenio-app-ils#587
(previously it displayed a standard message provided by `react-searchkit`)

Search: invalid queries error handling

---

src/lib/modules/SearchControls/SearchControls.js
src/lib/modules/SearchControls/__snapshots__/SearchControls.test.js.snap
src/semantic-ui/site/views/card.overrides

backoffice: fix spacing for facets

---

src/lib/forms/core/BaseForm/BaseForm.js
src/lib/pages/backoffice/Acquisition/Vendor/VendorEditor/VendorForm/VendorForm.js
src/lib/pages/backoffice/Document/DocumentForms/DocumentEditor/DocumentForm/DocumentForm.js
src/lib/pages/backoffice/EItem/EItemForms/EItemEditor/EItemForm/EItemForm.js
src/lib/pages/backoffice/ILL/Library/LibraryEditor/LibraryForm/LibraryForm.js
src/lib/pages/backoffice/Location/LocationForms/InternalLocationEditor/components/InternalLocationForm/InternalLocationForm.js
src/lib/pages/backoffice/Location/LocationForms/LocationEditor/components/LocationForm/Closures/ExceptionsField.js
src/lib/pages/backoffice/Location/LocationForms/LocationEditor/components/LocationForm/LocationForm.js
src/lib/pages/backoffice/Series/SeriesForms/SeriesEditor/components/SeriesForm/AccessUrls.js
src/lib/pages/backoffice/Series/SeriesForms/SeriesEditor/components/SeriesForm/SeriesForm.js

Forms: validate forms with yup

---

src/lib/api/base.js
src/lib/api/base.test.js
src/lib/history.js

axios: retry request on CSRF missing cookie/token error

---

src/lib/forms/components/UrlsField.js
src/lib/pages/backoffice/Document/DocumentForms/DocumentEditor/DocumentForm/DocumentBasicMetadata.js
src/lib/pages/backoffice/Document/DocumentForms/DocumentEditor/DocumentForm/components/LicensesField.js

Forms: fix field bugs

---

src/lib/config/defaultConfig.js
src/lib/pages/backoffice/Item/ItemForms/ItemEditor/ItemForm/ItemForm.js
src/lib/pages/frontsite/PatronProfile/PatronCurrentLoans/LoanExtendButton.js

Depends on #https://github.com/inveniosoftware/invenio-app-ils/pull/962

vocabulary: Adds item mediums vocabulary

---

src/lib/pages/backoffice/Acquisition/Order/OrderDetails/PaymentInformation.js
src/lib/pages/backoffice/Acquisition/Order/OrderSearch/OrderList/OrderListEntry.js

- render order payment information components only if payment exists

acq_orders: fixes for migrated records

---

src/lib/components/ILSMenu/ILSMenu.js

ILSMenu: add button to go to the search page

---

src/lib/pages/frontsite/PatronProfile/LoansListEntry.js
src/lib/pages/frontsite/PatronProfile/PatronPendingLoans/PatronPendingLoans.js

PendingLoans: display delivery method

---

src/lib/modules/SearchControls/SearchAggregationsMenu.js
src/semantic-ui/site/modules/dropdown.overrides

mobile: Fixes filters display

---

src/lib/modules/Literature/LiteratureCover.js
src/lib/modules/Series/__snapshots__/SeriesCard.test.js.snap

* Removes Placeholder component
when no url present

covers: Removes cover placeholders

---

src/lib/pages/backoffice/Item/ItemDetails/ItemMetadata/ItemMetadata.js
src/lib/pages/backoffice/Item/ItemForms/ItemEditor/ItemForm/ItemForm.js

* depends on inveniosoftware/invenio-app-ils#992

[depends on invenio-app-ils#992] backoffice: update form to allow multiple ISBNs

---

src/lib/forms/core/BaseForm/BaseForm.js
src/lib/forms/core/SelectorField.js
src/lib/modules/ESSelector/ESSelector.js
src/lib/pages/backoffice/Item/ItemForms/ItemEditor/ItemEditor.js
src/lib/pages/backoffice/Item/ItemForms/ItemEditor/ItemForm/ItemForm.js
src/lib/pages/backoffice/Item/ItemForms/ItemEditor/index.js

* Adds warning modal when updating the document
of an item that has past loans
* Disables edit button when item on loan
* closes https://github.com/inveniosoftware/invenio-app-ils/issues/228
While editing an item if it has past loans the form will display the document field disabled and with a informative message.

itemForm: Improves item edit

---

src/lib/config/defaultConfig.js
src/lib/pages/frontsite/DocumentRequests/DocumentRequestForm.js
src/lib/pages/frontsite/Documents/DocumentDetails/DocumentCirculation/DocumentEItems.js
src/lib/pages/frontsite/Documents/DocumentDetails/DocumentCirculation/LoanAvailability.js
src/lib/pages/frontsite/Documents/DocumentDetails/LoanRequestForm/LoanRequestForm.js

Closes #278 
The form to request an eitem has the medium type pre-filled with `ELECTRONIC`.
Screenshot:

FrontsiteLoanRequest: redirect to document request

---

src/lib/components/backoffice/UrlList/UrlList.js
src/lib/modules/Literature/LiteratureAccessUrls.js

* partially addresses https://github.com/CERNDocumentServer/cds-ils/issues/162

eitems: Updates url when login required

---

src/lib/components/backoffice/Sidebar/Sidebar.js
src/lib/index.js
src/lib/routes/backoffice/BackOfficeRoutesSwitch.js

* Needed for https://github.com/CERNDocumentServer/cds-ils/pull/240

overridable: Adds overrdiable components for importer

---

src/lib/modules/SearchControls/SearchAggregationsMenu.js

filters: fix checkbox not being clicked in mobile view

---

src/lib/config/defaultConfig.js

Closes CERNDocumentServer/cds-ils#222

facets: remove related content from literature search

---

src/lib/index.js

* exports `Media` component
* Needed for https://github.com/CERNDocumentServer/cds-ils/pull/264
* Blocked by https://github.com/inveniosoftware/react-invenio-app-ils/pull/321

responsive: exports Media component

---

src/lib/config/defaultConfig.js

* closes https://github.com/inveniosoftware/react-invenio-app-ils/issues/22
* needs https://github.com/inveniosoftware/react-searchkit/pull/172

Filters: Adds "has files" filter to eitems

---

src/lib/pages/backoffice/Series/SeriesDetails/SeriesUrls/SeriesUrls.js
src/lib/pages/backoffice/Series/SeriesForms/SeriesEditor/components/SeriesForm/AccessUrls.js
src/semantic-ui/site/elements/list.overrides

* It allows multiple selection
* Updated the display of the urls in the series
* Needs https://github.com/inveniosoftware/invenio-app-ils/pull/1019

series: Updates access_restriction

---

src/lib/modules/Document/DocumentCard/DocumentCard.js
src/lib/modules/Document/DocumentListEntry/DocumentListEntry.js
src/lib/modules/Document/DocumentListEntry/__snapshots__/DocumentListEntry.test.js.snap
src/lib/modules/Literature/LiteratureCover.js
src/lib/modules/Series/__snapshots__/SeriesCard.test.js.snap
src/semantic-ui/site/elements/image.overrides

covers: fix restricted doc cover in list view in frontsite

---

src/lib/components/backoffice/ExportSearchResults/ExportSearchResults.js
src/lib/config/defaultConfig.js
src/lib/forms/core/VocabularyField.js

- vocab max results window to 500
- max export results window to 4000

vocabularies: set vocab max results window to 500

---

src/lib/pages/backoffice/Document/DocumentDetails/DocumentMetadata/DocumentContents.js
src/lib/pages/backoffice/Document/DocumentForms/DocumentEditor/DocumentForm/DocumentContent.js
src/lib/pages/backoffice/Item/ItemDetails/ItemContent/ItemContent.js
src/lib/pages/backoffice/Item/ItemForms/ItemEditor/ItemForm/ItemForm.js

* Adds physical description to document
form and details page.
* Removes physical description from
item form and details page.
* Depends on https://github.com/inveniosoftware/invenio-app-ils/pull/1024

[BLOCKED]form: physical description

---

package-lock.json
package.json
src/lib/api/vocabularies/vocabulary.js
src/lib/forms/rjsf/RJSFCustomTemplates.js
src/lib/forms/rjsf/RJSForm.js
src/lib/forms/rjsf/RJSFormWrapper.js
src/lib/forms/rjsf/widgets/RJSFVocabulary.js
src/lib/forms/rjsf/widgets/RJSFVocabularySearch.js
src/lib/pages/backoffice/Document/DocumentForms/DocumentEditor/schema.js
src/lib/pages/backoffice/Document/DocumentForms/DocumentEditor/uiSchema.js
src/lib/pages/backoffice/DocumentRequest/DocumentRequestDetails/DocumentRequestActions/DocumentRequestActions.js
src/lib/pages/backoffice/DocumentRequest/DocumentRequestDetails/DocumentRequestDetails.js
src/lib/pages/backoffice/DocumentRequest/DocumentRequestEditor/DocumentRequestEditor.js
src/lib/pages/backoffice/DocumentRequest/DocumentRequestEditor/index.js
src/lib/pages/backoffice/DocumentRequest/DocumentRequestEditor/schema.js
src/lib/pages/backoffice/DocumentRequest/DocumentRequestEditor/uiSchema.js
src/lib/routes/backoffice/BackOfficeRoutesSwitch.js
src/lib/routes/backoffice/backofficeUrls.js

* adds RJSF dependency
* adds support of grid layout to RJSF
* adds widgets for vocabularies
* adds a draft schema for the document
* adds a first implementation of the document request form

Add react-jsonschema-forms and draft Doc Req form

---

src/lib/components/backoffice/MetadataTable/MetadataTable.js
src/lib/components/utils.js
src/lib/modules/Document/DocumentMetadataExtensions.js
src/lib/modules/Document/__snapshots__/DocumentMetadataExtensions.test.js.snap

* Fix display of boolean values

extensions: boolean values

---

src/lib/config/common.js
src/lib/modules/Series/SeriesAccess.js
src/lib/pages/backoffice/Document/DocumentForms/DocumentEditor/schema.js
src/testData/documents.json

* change periodical issue naming

[DEPENDS ON IAILS#1040] document: add document type

---

src/lib/pages/backoffice/ILL/BorrowingRequest/BorrowingRequestEditor/BorrowingRequestForm/Payment.js

* Payment field is no longer required
* closes https://github.com/CERNDocumentServer/cds-ils/issues/328

[DEPENDS ON IAI #1038] ill: borrowing request

---

src/lib/config/common.js
src/lib/config/defaultConfig.js
src/lib/pages/backoffice/Document/DocumentDetails/DocumentMetadata/DocumentContents.js
src/lib/pages/backoffice/Document/DocumentForms/DocumentEditor/DocumentForm/DocumentAdditionalInfo.js
src/lib/pages/backoffice/Document/DocumentForms/DocumentEditor/DocumentForm/DocumentBasicMetadata.js
src/lib/pages/backoffice/Document/DocumentForms/DocumentEditor/DocumentForm/DocumentForm.js
src/lib/pages/backoffice/Document/DocumentForms/DocumentEditor/DocumentForm/DocumentLicensesCopyright.js
src/lib/pages/backoffice/Document/DocumentForms/DocumentEditor/DocumentForm/DocumentPublishing.js
src/lib/pages/backoffice/Document/DocumentForms/DocumentEditor/DocumentForm/components/Identifiers.js
src/lib/pages/backoffice/Document/DocumentForms/DocumentEditor/DocumentForm/components/Subjects.js
src/lib/pages/backoffice/Series/SeriesForms/SeriesEditor/components/SeriesForm/SeriesForm.js

* Material and subject are vocabularies now
* Moved up the fields Imprint, Identifiers
and Alternative titles
* closes https://github.com/CERNDocumentServer/cds-ils/issues/330
* depends on https://github.com/inveniosoftware/invenio-app-ils/pull/1042

[DEPENDS ON IAI #1042] documentForm: updates

---

cypress/integration/frontsite/footer.test.spec.js
cypress/integration/frontsite/profile.test.spec.js

* Fixed minor bugs
* Some tests are still failing due to 429 error, CORS or CSRF token errors

cypress: minor fixes

---

src/lib/components/Breadcrumbs/Breadcrumbs.js
src/lib/components/ILSMenu/ILSMenu.js
src/lib/components/Media/index.js
src/lib/components/Media/media.js
src/lib/components/SearchBar/SearchBarILS.js
src/lib/components/SearchBar/SearchBarOverrides.js
src/lib/components/SearchBar/__snapshots__/SearchBarILS.test.js.snap
src/lib/components/utils.js
src/lib/modules/ESSelector/ESSelectorLoanRequest.js
src/lib/modules/Series/SeriesLiteratureSearch/SeriesLiteratureSearch.js
src/lib/modules/Series/SeriesLiteratureSearch/__snapshots__/SeriesLiteratureSearch.test.js.snap
src/lib/pages/backoffice/Item/ItemDetails/ItemActionMenu/ItemActionMenu.js
src/lib/pages/frontsite/Documents/DocumentDetails/DocumentDetails.js
src/lib/pages/frontsite/Home/Headline/HomeSearchBar.js
src/lib/pages/frontsite/Literature/LiteratureSearch/LiteratureSearch.js
src/lib/pages/frontsite/Series/SeriesDetails/SeriesDetails.js
src/semantic-ui/site/collections/breadcrumb.overrides
src/semantic-ui/site/globals/site.overrides
src/setupTests.js

* Fixes minor responsive issues
* Fixes breadcrumbs alignment
* closes https://github.com/CERNDocumentServer/cds-ils/issues/24

fixes: responsive

---

src/lib/modules/Document/DocumentContent.js

Closes https://github.com/orgs/inveniosoftware/projects/19#card-56533505

frontsite: fix not displayed table of content

---

src/lib/config/defaultConfig.js
src/lib/modules/ESSelector/ESSelectorLoanRequest.js
src/lib/modules/Loan/backoffice/LoanList/LoanListEntry.js
src/lib/pages/backoffice/Document/DocumentDetails/DocumentSummary/DocumentSummary.js
src/lib/pages/backoffice/Document/DocumentDetails/state/actions.js
src/lib/pages/backoffice/Loan/LoanDetails/LoanMetadata/LoanMetadata.js
src/lib/pages/frontsite/Documents/DocumentDetails/LoanRequestForm/LoanRequestForm.js
src/lib/pages/frontsite/PatronProfile/PatronPendingLoans/PatronPendingLoans.js
src/semantic-ui/site/globals/site.overrides

Closes CERNDocumentServer/cds-ils#359
- removed overridable delivery icon and added it in the config

frontsite: fixes in loan request form

---

src/lib/config/common.js

Depends on https://github.com/inveniosoftware/invenio-app-ils/pull/1066

[BLOCKED]proceedings: rename from proceeding

---

src/lib/config/defaultConfig.js
src/lib/modules/Document/DocumentCard/DocumentCard.js
src/lib/modules/Series/SeriesCard.js
src/lib/modules/Series/__snapshots__/SeriesCard.test.js.snap
src/lib/pages/backoffice/Document/DocumentEditor/uiSchema.js
src/lib/pages/backoffice/Series/SeriesDetails/SeriesContent/SeriesContent.js
src/lib/pages/backoffice/Series/SeriesEditor/uiSchema.js

- fix vocabulary fields in forms

Authors and vocabulary values in forms

---

src/lib/pages/backoffice/DocumentRequest/DocumentRequestDetails/DocumentRequestSteps/DocumentRequestStepPanels/ChooseProviderStepPanel/ChooseProviderStepPanel.js

Closes https://github.com/inveniosoftware/invenio-app-ils/issues/1069

lit request: do not filter acq/ill by status

---

src/lib/pages/backoffice/Patron/PatronDetails/PatronCurrentLoans/PatronCurrentLoans.js
src/lib/pages/backoffice/Patron/PatronDetails/PatronCurrentLoans/__snapshots__/PatronCurrentLoans.test.js.snap
src/lib/pages/backoffice/Patron/PatronDetails/PatronPastLoans/PatronPastLoans.js

patronDetails: fix links

---

src/lib/index.js
src/lib/modules/Document/DocumentCard/DocumentCard.js
src/lib/modules/Document/DocumentListEntry/DocumentListEntry.js
src/lib/modules/Document/DocumentListEntry/__snapshots__/DocumentListEntry.test.js.snap
src/lib/modules/Loan/backoffice/LoanList/LoanDates.js
src/lib/pages/frontsite/Documents/DocumentDetails/DocumentCirculation/DocumentEItems.js
src/lib/pages/frontsite/Literature/LiteratureSearch/LiteratureSearch.js
src/lib/pages/frontsite/Literature/LiteratureSearch/__snapshots__/LiteratureSearch.test.js.snap

- add overridable components for standard number in frontsite card and list results view
- fix iso loan dates in search results

add overridable cmp for standard number

---

src/lib/modules/Series/SeriesLinks.js
src/lib/pages/backoffice/Series/SeriesDetails/SeriesUrls/SeriesUrls.js
src/lib/pages/backoffice/Series/SeriesEditor/schema.js
src/lib/pages/backoffice/Series/SeriesEditor/uiSchema.js

Closes https://github.com/CERNDocumentServer/cds-migrator-kit/issues/129
Depends on https://github.com/inveniosoftware/invenio-app-ils/pull/1077

[BLOCKED]series: add login_required to access_urls

---

src/lib/pages/backoffice/Acquisition/Order/OrderDetails/OrderDetails.js
src/lib/pages/backoffice/Acquisition/Order/OrderDetails/OrderInformation.js
src/lib/pages/backoffice/Acquisition/Order/OrderEditor/schema.js
src/lib/pages/backoffice/Acquisition/Order/OrderSearch/OrderList/OrderListEntry.js

Closes https://github.com/CERNDocumentServer/cds-migrator-kit/issues/135

order: display creation date, do not require order date

---

src/lib/pages/backoffice/ILL/BorrowingRequest/BorrowingRequestDetails/BorrowingRequestDetails.js
src/lib/pages/backoffice/ILL/BorrowingRequest/BorrowingRequestDetails/BorrowingRequestMetadata.js

Closes https://github.com/CERNDocumentServer/cds-migrator-kit/issues/138

brwReq: display creation date

---

cypress/integration/frontsite/search.test.spec.js
src/lib/config/defaultConfig.js
src/lib/modules/Document/DocumentCard/DocumentCard.js

Closes https://github.com/CERNDocumentServer/cds-ils/issues/356

literatureSearch: facet fixes

---

src/lib/pages/frontsite/Home/Headline/Headline.js
src/lib/pages/frontsite/Home/Sections/SectionsWrapper.js

Closes https://github.com/inveniosoftware/react-invenio-app-ils/issues/385

homepage: reorder quick access buttons

---

src/lib/pages/frontsite/PatronProfile/PatronCurrentLoans/LoanExtendButton.js
src/lib/pages/frontsite/PatronProfile/PatronOverview/PatronOverview.js
src/lib/pages/frontsite/PatronProfile/PatronPastLoans/PatronPastLoans.js
src/lib/pages/frontsite/PatronProfile/PatronPendingLoans/PatronPendingLoans.js
src/lib/pages/frontsite/PatronProfile/PatronProfile.js
src/semantic-ui/site/views/statistic.overrides

Closes https://github.com/inveniosoftware/react-invenio-app-ils/issues/388

patron profile: small fixes

---

src/lib/pages/backoffice/Acquisition/Order/OrderSearch/OrderList/OrderListEntry.js
src/lib/pages/backoffice/ILL/BorrowingRequest/BorrowingRequestDetails/BorrowingRequestDetails.js
src/lib/pages/backoffice/ILL/BorrowingRequest/BorrowingRequestSearch/BorrowingRequestList/BorrowingRequestListEntry.js

* acq: display document title in search results

ill: display document title in search results

---

src/lib/pages/backoffice/Document/DocumentEditor/uiSchema.js

Reorder document create form.
closes https://github.com/CERNDocumentServer/cds-ils/issues/331

Document creation formulary reorder

---

src/lib/pages/backoffice/Document/DocumentEditor/schema.js

Make languages mandatory.
closes https://github.com/CERNDocumentServer/cds-ils/issues/544

document form: mandatory language fields

---

package-lock.json
src/lib/modules/Document/DocumentCard/DocumentCard.js
src/lib/modules/Items/backoffice/ItemListEntry.js
src/lib/pages/backoffice/Document/DocumentDetails/DocumentPurchaseOrders/DocumentPurchaseOrders.js
src/lib/pages/backoffice/Document/DocumentDetails/DocumentPurchaseOrders/index.js
src/lib/pages/backoffice/Loan/LoanDetails/LoanDetails.js
src/lib/pages/backoffice/Loan/LoanDetails/LoanOverbookedWarning/LoanOverbookedWarning.js

* check in: location highlight fixes

check in: highlight fixes

---

src/lib/pages/frontsite/Documents/DocumentDetails/DocumentPanel/DocumentPanel.js
src/lib/pages/frontsite/Documents/DocumentDetails/DocumentPanel/DocumentPanelMobile.js

Make sure that there is a proper space between the publisher and the publication_year.

DocumentPanel: fix data display

---

src/lib/pages/frontsite/DocumentRequests/DocumentRequestForm.js
src/lib/pages/frontsite/Documents/DocumentDetails/DocumentCirculation/DocumentCirculation.js
src/lib/pages/frontsite/Documents/DocumentDetails/DocumentCirculation/DocumentEItems.js

closes https://github.com/inveniosoftware/react-invenio-app-ils/issues/354

documentRequest:added prefilled fields to the literature request when requesting an e-book

---

src/lib/forms/mapFields.js
src/lib/pages/backoffice/Document/DocumentEditor/DocumentEditor.js
src/lib/pages/backoffice/DocumentRequest/DocumentRequestDetails/DocumentRequestSteps/DocumentRequestStepPanels/ChooseDocumentStepPanel/ChooseDocumentStepPanel.js
src/lib/pages/backoffice/DocumentRequest/DocumentRequestDetails/DocumentRequestSteps/DocumentRequestStepPanels/ChooseProviderStepPanel/ChooseProviderStepPanel.js
src/lib/pages/backoffice/DocumentRequest/DocumentRequestEditor/DocumentRequestEditor.js

more fields are now being prefilled in the document create and acquisition order form
closes https://github.com/CERNDocumentServer/cds-ils/issues/536

Document&AcquisitionOrder: now pre-fills additional fields

---

src/lib/components/ILSFooter/ILSFooter.js
src/lib/config/defaultConfig.js
src/lib/pages/frontsite/Literature/LiteratureSearch/LiteratureSearch.js
src/lib/pages/frontsite/Literature/LiteratureSearch/SearchGuideLink/SearchGuideLink.js

Add a link to the search guide in invenio's footer.
Add a link to the search guide in the LiteratureSearch page.
closes: https://github.com/CERNDocumentServer/cds-ils/issues/50
requires: https://github.com/inveniosoftware/invenio-app-ils/pull/1120

SearchGuide: add links to the search guide.

---

src/lib/pages/frontsite/Documents/DocumentDetails/DocumentItems/DocumentItem.js

Set one of the labels in the 'where to find' table.

DocumentItem: easier to understand label

---

src/lib/components/HttpErrors/index.js
src/lib/index.js

Export the base HttpError component for customizability

HttpError: export base component

---

src/lib/pages/frontsite/Documents/DocumentDetails/DocumentItems/DocumentItemBody.js
src/lib/pages/frontsite/Documents/DocumentDetails/DocumentItems/DocumentItems.js

DocumentItem: show items on loan in 'where to find' section

---

src/lib/pages/backoffice/Loan/LoanSearch/LoanSearch.js

closes: https://github.com/CERNDocumentServer/cds-ils/issues/639
requires: https://github.com/inveniosoftware/invenio-app-ils/pull/1136

Loans: Allow downloading all the loans in csv/json

---

src/lib/api/base.js

see https://github.com/inveniosoftware/invenio-rest/commit/3e2a4d03270f19e494457f14d8a7626210115708#diff-772073f872b7df7d3d87c85bc2b74c05f6dbf656778c9af7f0bb6aeab3849988R196

global: fix headers compatibility with invenio-rest

---

src/lib/modules/Document/DocumentConference.js
src/lib/pages/backoffice/DocumentRequest/DocumentRequestDetails/DocumentRequestSteps/DocumentRequestStepsHeader.js
src/lib/pages/frontsite/PatronProfile/PatronPastLoans/PatronPastLoans.js

* name changes
* closes https://github.com/CERNDocumentServer/cds-ils/issues/534

document: overridable conferences component

---

src/lib/pages/backoffice/Patron/PatronDetails/ItemsCheckout/state/actions.js
src/lib/pages/backoffice/Patron/PatronDetails/ItemsSearch/ItemsSearch.js
src/lib/pages/backoffice/Patron/PatronDetails/ItemsSearch/index.js
src/lib/pages/backoffice/Patron/PatronDetails/ItemsSearch/state/actions.js
src/lib/pages/backoffice/Patron/PatronDetails/ItemsSearch/state/actions.test.js
src/lib/pages/backoffice/Patron/PatronDetails/ItemsSearch/state/reducer.js
src/lib/pages/backoffice/Patron/PatronDetails/ItemsSearch/state/reducer.test.js
src/lib/pages/backoffice/Patron/PatronDetails/ItemsSearch/state/types.js

Now automatically checks out the found item if a barcode is pasted in the checkout section of the patron details page.
closes https://github.com/CERNDocumentServer/cds-ils/issues/546

Patron: auto-checkout on paste

---

src/lib/config/defaultConfig.js
src/lib/pages/frontsite/PatronProfile/LoansList.js
src/lib/pages/frontsite/PatronProfile/PatronCurrentDocumentRequests/PatronCurrentDocumentRequests.js
src/lib/pages/frontsite/PatronProfile/PatronCurrentLoans/PatronCurrentLoans.js
src/lib/pages/frontsite/PatronProfile/PatronPagination.js
src/lib/pages/frontsite/PatronProfile/PatronPastDocumentRequests/PatronPastDocumentRequests.js
src/lib/pages/frontsite/PatronProfile/PatronPastLoans/PatronPastLoans.js
src/lib/pages/frontsite/PatronProfile/PatronPendingLoans/PatronPendingLoans.js
src/lib/pages/frontsite/PatronProfile/PatronShowLink.js
src/semantic-ui/site/globals/site.overrides

Add information about the total loans / document requests of each list.
Allow showing all loans / document requests.
Allow revert to using pagination.
Fix pagination in lists that display document requests.
closes CERNDocumentServer/cds-ils#672
Current Loans:
Current Loans show all:
Pending Loans
Pending Loans show all:
Requests for new literature:
Requests for new Literature show all:
Past Loans:
Past Requests for new Literature:

PatronProfile: add pagination element at the beginning of the lists

---

CHANGES.md
package-lock.json
package.json
src/lib/modules/Document/DocumentAuthors.js
src/lib/modules/Document/DocumentCard/DocumentCard.js

authors: fix "et al." display

---

src/lib/modules/Document/DocumentConference.js

This pr is passing the needed props to the `Overridable` component so that these are available when you override the `DocumentConference` component.
:rotating_light: Please review the [guidelines for contributing](https://invenio.readthedocs.io/en/latest/community/contributing/contribution-guide.html) to Invenio.
> Green light on all GitHub Actions status checks is required in order to merge your PR. Check your code additions will fail neither code linting checks nor tests and will not decrease test coverage.
See [copyright and license policy](https://invenio.readthedocs.io/en/latest/community/contributing/maintainers-guide/copyright-policy.html) for details.
By using GitHub, you have already agreed to the [GitHub’s Terms of …

document: pass needed props to overrisable context

---

CHANGES.md
package-lock.json
package.json

Please describe briefly your pull request.
:rotating_light: Please review the [guidelines for contributing](https://invenio.readthedocs.io/en/latest/community/contributing/contribution-guide.html) to Invenio.
> Green light on all GitHub Actions status checks is required in order to merge your PR. Check your code additions will fail neither code linting checks nor tests and will not decrease test coverage.
See [copyright and license policy](https://invenio.readthedocs.io/en/latest/community/contributing/maintainers-guide/copyright-policy.html) for details.
By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contributions-under-repository-license) including that:
1. …

release: v1.0.0-alpha.66

---

src/lib/pages/backoffice/Acquisition/Order/OrderDetails/OrderLines.js
src/lib/pages/backoffice/Acquisition/Order/OrderEditor/schema.js
src/lib/pages/backoffice/DocumentRequest/DocumentRequestDetails/DocumentRequestMetadata.js
src/lib/pages/backoffice/DocumentRequest/DocumentRequestDetails/DocumentRequestSteps/DocumentRequestStepPanels/ChooseDocumentStepPanel/ChooseDocumentStepPanel.js
src/lib/pages/backoffice/DocumentRequest/DocumentRequestDetails/DocumentRequestSteps/DocumentRequestStepPanels/ChooseProviderStepPanel/ChooseProviderStepPanel.js
src/lib/pages/backoffice/DocumentRequest/DocumentRequestEditor/schema.js
src/lib/pages/backoffice/ILL/BorrowingRequest/BorrowingRequestDetails/BorrowingRequestPayment.js
src/lib/pages/backoffice/ILL/BorrowingRequest/BorrowingRequestEditor/schema.js
src/lib/pages/backoffice/ILL/BorrowingRequest/BorrowingRequestEditor/uiSchema.js
src/lib/pages/frontsite/DocumentRequests/DocumentRequestForm.js

* fix mapping for pages, payment info and identifiers in doc and acquisition order creation forms
* add budget code field for borrowing request creation form
* fix some labels and placeholders
* closes https://github.com/inveniosoftware/react-invenio-app-ils/issues/352
* back-end corresponding PR: https://github.com/inveniosoftware/invenio-app-ils/pull/1160
Multiple identifiers prefill preview:

form prefilling: mapping and labels fix

---

src/lib/modules/Series/SeriesLiteratureSearch/SeriesLiteratureSearch.js
src/lib/modules/Series/SeriesLiteratureSearch/__snapshots__/SeriesLiteratureSearch.test.js.snap

* add popup with volume search hint
* closes https://github.com/inveniosoftware/invenio-app-ils/issues/729
Popup and icon preview:

search for volumes in series: volume field search

---

src/lib/modules/SearchControls/SearchControls.js
src/lib/modules/SearchControls/SearchControls.test.js
src/lib/modules/SearchControls/SearchControlsMobile.js
src/lib/modules/SearchControls/SearchFooter.js
src/lib/modules/SearchControls/__snapshots__/SearchControls.test.js.snap
src/lib/modules/Series/SeriesLiteratureSearch/__snapshots__/SeriesLiteratureSearch.test.js.snap
src/lib/pages/frontsite/Literature/LiteratureSearch/LiteratureSearch.js
src/lib/pages/frontsite/Literature/LiteratureSearch/SearchAggregation.js
src/lib/pages/frontsite/Literature/LiteratureSearch/SearchMessage/SearchMessage.js
src/semantic-ui/site/globals/site.overrides

* change design of search message depending on search result
* remove rendering of some components depending on search result
* closes https://github.com/inveniosoftware/react-invenio-app-ils/issues/386
Computer and mobile versions preview:

literature request: search message

---

src/lib/pages/frontsite/Documents/DocumentDetails/DocumentPanel/DocumentPanel.js
src/lib/pages/frontsite/Documents/DocumentDetails/DocumentPanel/DocumentPanelMobile.js
src/lib/pages/frontsite/Series/SeriesDetails/SeriesPanel/SeriesPanel.js
src/lib/pages/frontsite/Series/SeriesDetails/SeriesPanel/SeriesPanelMobile.js
src/semantic-ui/site/elements/image.overrides
src/semantic-ui/site/elements/segment.overrides
src/semantic-ui/site/views/card.overrides

* align book covers in a front page and in the series details page, frontsite
* add box shadows for covers
* closes https://github.com/inveniosoftware/react-invenio-app-ils/issues/551
Alignment and shadows preview:
Book details page preview:

Improve book covers

---

CHANGES.md
package-lock.json
package.json
src/lib/modules/Patron/PatronBulkExtendLoans/PatronBulkExtendLoans.js
src/lib/pages/backoffice/DocumentRequest/DocumentRequestSearch/DocumentRequestListEntry.js
src/lib/pages/frontsite/PatronProfile/LoansListEntry.js
src/lib/pages/frontsite/PatronProfile/PatronCurrentDocumentRequests/PatronCurrentDocumentRequests.js
src/lib/pages/frontsite/PatronProfile/PatronCurrentLoans/PatronCurrentLoans.js
src/lib/pages/frontsite/PatronProfile/PatronPastDocumentRequests/PatronPastDocumentRequests.js
src/lib/pages/frontsite/PatronProfile/PatronPastLoans/PatronPastLoans.js
src/lib/pages/frontsite/PatronProfile/PatronPendingLoans/PatronPendingLoans.js
src/lib/pages/frontsite/PatronProfile/PatronShowLink.js
src/semantic-ui/site/globals/site.overrides

- removes links to literature for past loans and requests, as they might not exist anymore in the catalogue
- fix a few UI issues

patron: make past loans not clickable

---

src/lib/modules/Series/SeriesAlternativeTitles.js
src/lib/pages/backoffice/Document/DocumentDetails/DocumentMetadata/DocumentMetadataGeneral.js
src/lib/pages/frontsite/Series/SeriesDetails/SeriesDetails.js

AlternativeTitle: Pass default if type key doesn't exist in data object

---

src/lib/modules/ESSelector/ESSelector.js
src/lib/modules/ESSelector/HitsSearch.js
src/lib/pages/backoffice/Item/ItemDetails/ItemActionMenu/ItemActionMenu.js

Fixes: #581 
- Fixed debounce search function by not re-defining it in every re-render and not send request to backend on every re-render.
- Updated Functionality to only auto-checkout when only 1 result is found and enter is pressed.

modules: HitsSearch: Fixed debounce search function to not send requests to backend on every keystroke

---

src/lib/config/defaultConfig.js
src/lib/pages/frontsite/Documents/DocumentDetails/LoanRequestForm/LoanRequestForm.js

Closes: https://github.com/CERNDocumentServer/cds-ils/issues/835

frontsite: LoanRequestForm: Added loan request offset start date to be configurable

---

src/lib/components/backoffice/PaymentInformation/PaymentInformation.js
src/lib/components/backoffice/PaymentInformation/index.js
src/lib/config/defaultConfig.js
src/lib/index.js
src/lib/pages/backoffice/Acquisition/Order/OrderDetails/OrderDetails.js
src/lib/pages/backoffice/Acquisition/Order/OrderDetails/OrderLines.js
src/lib/pages/backoffice/Acquisition/Order/OrderDetails/PaymentInformation.js
src/lib/pages/backoffice/ILL/BorrowingRequest/BorrowingRequestDetails/BorrowingRequestMetadata.js
src/lib/pages/backoffice/ILL/BorrowingRequest/BorrowingRequestDetails/BorrowingRequestPayment.js
src/lib/pages/backoffice/ILL/BorrowingRequest/BorrowingRequestDetails/BorrowingRequestStatistics.js
src/lib/pages/backoffice/ILL/BorrowingRequest/BorrowingRequestEditor/schema.js
src/lib/pages/backoffice/ILL/BorrowingRequest/BorrowingRequestSearch/BorrowingRequestList/BorrowingRequestListEntry.js

Closes: https://github.com/CERNDocumentServer/cds-ils/issues/729

backoffice: PaymentInformation: Extract PaymentInformation Grid as a Component and make it Overridable

---

src/lib/pages/backoffice/Document/DocumentDetails/DocumentActionMenu/DocumentActionMenu.js
src/lib/pages/backoffice/Document/DocumentDetails/DocumentBorrowingRequests/DocumentBorrowingRequests.js
src/lib/pages/backoffice/Document/DocumentDetails/DocumentBorrowingRequests/index.js
src/lib/pages/backoffice/Document/DocumentDetails/DocumentContent.js
src/lib/pages/backoffice/Document/DocumentDetails/DocumentDetails.js

Closes: https://github.com/CERNDocumentServer/cds-ils/issues/823

backoffice: DocumentDetails: Show Ongoing Interlibrary loans in DocumentDetails page

---

src/lib/api/ill/borrowingRequest.js

Fixes: https://github.com/CERNDocumentServer/cds-ils/issues/857
Ref: https://github.com/inveniosoftware/invenio-rdm-records/blob/82f6e1ecf11cb1c24cf4b4208bea8255003dd97e/invenio_rdm_records/assets/semantic-ui/js/invenio_rdm_records/src/deposit/api/DepositApiClient.js#L157

api: ill: Pass empty json payload in POST request for extension actions

---

src/lib/api/base.js
src/lib/components/Error/Error.js
src/lib/components/HttpErrors/HttpErrors.js
src/lib/components/HttpErrors/index.js
src/lib/components/Notifications/actions.js
src/lib/pages/frontsite/ErrorsPage/ErrorsPage.js

Fixes: https://github.com/CERNDocumentServer/cds-ils/issues/849

components: Notifications: Configure error notification to not be added for http code 410

---

src/lib/forms/rjsf/RJSFCustomTemplates.js
src/lib/forms/rjsf/RJSForm.js
src/lib/forms/rjsf/utils.js

Fixes: https://github.com/CERNDocumentServer/cds-ils/issues/853

forms: rjsf: Extend ignoreEnterEvent for dynamically created text fields

---

src/lib/pages/backoffice/Acquisition/Order/OrderSearch/OrderList/OrderListEntry.js
src/lib/pages/backoffice/Patron/PatronDetails/PatronDocumentRequests/PatronDocumentRequests.js
src/lib/pages/backoffice/Patron/PatronDetails/PatronDocumentRequests/__snapshots__/PatronDocumentRequests.test.js.snap

Fixes: https://github.com/CERNDocumentServer/cds-ils/issues/821

backoffice: Use Truncate for OrdersList and Patrons Doc Requests table

---

src/lib/pages/backoffice/EItem/EItemSearch/EItemSearch.js

Resolves: https://github.com/CERNDocumentServer/cds-ils/issues/739

backoffice: EItemSearch: Add source button in helper fields

---

src/lib/api/series/series.js
src/lib/index.js
src/lib/modules/Series/SeriesCardGroup/SeriesCardGroup.js
src/lib/modules/Series/SeriesCardGroup/index.js

Resolves: https://github.com/CERNDocumentServer/cds-ils/issues/728
Related: https://github.com/CERNDocumentServer/cds-ils/pull/864

Feature: Add SeriesCardGroup component and add filters in seriesApi

---

src/lib/pages/frontsite/Documents/DocumentDetails/DocumentPanel/DocumentTitle.js
src/semantic-ui/site/collections/grid.overrides
src/semantic-ui/site/globals/site.overrides

* closes https://github.com/CERNDocumentServer/cds-ils/issues/734
* Related: #595

frontsite: DocumentTitle: Decrease spacing between the tags and title

---

src/lib/components/backoffice/Sidebar/Sidebar.js

Fixes: https://github.com/CERNDocumentServer/cds-ils/issues/871

backoffice: SideBar: Make SideBar Catalogue menu overridable

---

src/lib/pages/backoffice/Patron/PatronDetails/ItemsSearch/ItemsSearch.js
src/lib/pages/backoffice/Patron/PatronDetails/ItemsSearch/index.js
src/lib/pages/backoffice/Patron/PatronDetails/ItemsSearch/state/actions.js

backoffice: PatronDetails: Clear search bar if checkout is successful

---

src/lib/config/common.js
src/lib/config/defaultConfig.js
src/lib/modules/Document/DocumentCard/DocumentCard.js
src/lib/modules/Document/DocumentEItemUrls.js
src/lib/modules/Document/DocumentListEntry/DocumentListEntry.js
src/lib/pages/backoffice/Document/DocumentDetails/DocumentEItems/DocumentEItems.js
src/lib/pages/backoffice/EItem/EItemDetails/EItemHeader.js
src/lib/pages/backoffice/EItem/EItemEditor/schema.js
src/lib/pages/backoffice/EItem/EItemEditor/uiSchema.js
src/lib/pages/backoffice/EItem/EItemSearch/EItemListEntry.js

closes: https://github.com/CERNDocumentServer/cds-ils/issues/805
closes: https://github.com/CERNDocumentServer/cds-ils/issues/865

EItem: Accomodate EItem type for facets, details page, cards and editor

---

src/lib/config/defaultConfig.js
src/lib/index.js
src/lib/pages/backoffice/Item/ItemDetails/ItemCirculation/ItemCirculation.js
src/lib/pages/backoffice/Item/ItemDetails/ItemMetadata/ItemMetadata.js
src/lib/pages/backoffice/Item/ItemEditor/schema.js
src/lib/pages/backoffice/Item/ItemEditor/uiSchema.js
src/lib/pages/frontsite/Documents/DocumentDetails/DocumentCirculation/DocumentCirculation.js
src/lib/pages/frontsite/Documents/DocumentDetails/DocumentCirculation/DocumentEItems.js
src/lib/pages/frontsite/Documents/DocumentDetails/DocumentItems/DocumentItem.js
src/lib/pages/frontsite/Documents/DocumentDetails/DocumentItems/DocumentItemBody.js
src/lib/pages/frontsite/Documents/DocumentDetails/DocumentItems/DocumentTabs.js
src/lib/pages/frontsite/Documents/DocumentDetails/DocumentPanel/DocumentPanel.js
src/lib/pages/frontsite/Documents/DocumentDetails/LoanRequestForm/LoanRequestForm.js

Closes: https://github.com/CERNDocumentServer/cds-ils/issues/834

fronsite: DocumentDetails: Add Overridable Ids to show maps and shelf link in overlay

---

src/lib/modules/Document/DocumentCard/DocumentCard.js
src/lib/modules/Document/DocumentListEntry/DocumentListEntry.js
src/lib/modules/Document/backoffice/DocumentList/DocumentListEntry.js
src/lib/modules/Document/utils.js
src/lib/modules/Series/SeriesCard.js
src/lib/modules/Series/SeriesListEntry.js
src/lib/pages/backoffice/Acquisition/Order/OrderDetails/OrderLines.js
src/lib/pages/backoffice/Acquisition/Order/OrderSearch/OrderList/OrderListEntry.js
src/lib/pages/backoffice/ILL/BorrowingRequest/BorrowingRequestDetails/BorrowingRequestDetails.js
src/lib/pages/backoffice/ILL/BorrowingRequest/BorrowingRequestSearch/BorrowingRequestList/BorrowingRequestListEntry.js
src/lib/pages/backoffice/Series/SeriesSearch/SeriesListEntry.js

closes: https://github.com/CERNDocumentServer/cds-ils/issues/761
DocumentCard:
DocumentList:
Frontsite:
Backoffice:
BrwReqList:
BrwReqDetails:
OrdersList:
OrdersDetails:

Display subtitles

---

src/lib/index.js
src/lib/pages/backoffice/Document/DocumentDetails/DocumentItems/DocumentItems.js
src/lib/pages/backoffice/Document/DocumentDetails/DocumentItems/__snapshots__/DocumentItems.test.js.snap

closes: https://github.com/CERNDocumentServer/cds-ils/issues/904

backoffice: DocumentItems: Update DocumentItems to be overridable

---

src/lib/pages/frontsite/Documents/DocumentDetails/DocumentItems/DocumentItem.js
src/lib/pages/frontsite/Documents/DocumentDetails/DocumentItems/DocumentItemBody.js
src/lib/pages/frontsite/Documents/DocumentDetails/DocumentItems/DocumentItems.js
src/lib/pages/frontsite/Documents/DocumentDetails/DocumentItems/DocumentTabs.js

related: https://github.com/CERNDocumentServer/cds-ils/pull/910

frontsite: DocumentItems: Add documentDetails to component props

---

src/lib/modules/Document/DocumentCard/DocumentCard.js
src/lib/modules/Series/SeriesCard.js

DocumentCard and SeriesCard: Move subtitle before authors

---

src/lib/pages/frontsite/SelfCheckout/ManualCheckout.js
src/lib/pages/frontsite/SelfCheckout/SelfCheckout.js
src/lib/pages/frontsite/SelfCheckout/SelfCheckoutModal/SelfCheckoutModal.js

self-checkout: allow to input the barcode manually

---

src/lib/api/locations/location.js
src/lib/api/locations/serializer.js
src/lib/modules/Location/LocationDatePicker.js
src/lib/pages/backoffice/Loan/LoanDetails/LoanUpdateDates/LoanUpdateDates.js

Closes: https://github.com/CERNDocumentServer/cds-ils/issues/967

Closings: The backoffice calendar no longer allows for selecting dates during which the location is closed

---

src/lib/modules/Relations/backoffice/components/ExistingRelations.js

Closes: https://github.com/CERNDocumentServer/cds-ils/issues/991

backoffice: fix relations table only showing items on the first page

---

src/lib/modules/Patron/PatronBulkExtendLoans/PatronBulkExtendLoans.js
src/lib/pages/backoffice/Patron/PatronDetails/PatronDetails.js
src/lib/pages/frontsite/PatronProfile/PatronCurrentLoans/PatronCurrentLoans.js

Closes: https://github.com/CERNDocumentServer/cds-ils/issues/785

ui: Button to extend all loans is disabled instead of hidden

---

src/lib/config/defaultConfig.js
src/lib/modules/ESSelector/ESSelectorLoanRequest.js
src/lib/pages/frontsite/Documents/DocumentDetails/LoanRequestForm/LoanRequestForm.js

closes: https://github.com/CERNDocumentServer/cds-ils/issues/968

backoffice: added NOT-SPECIFIED delivery method
